version: '2'
services:
  pyo_db:
    image: mysql:5.7.22
    ports:
      - "4000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: procesosyoperaciones
      MYSQL_USER: user
      MYSQL_PASSWORD: procesosyoperaciones
      MYSQL_DATABASE: ProcesosOperaciones_production
      MYSQL_HOST: pyo_db
  pyo_ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails s -e production -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: 1177bac74d7619cb4b725f91897929279cb12c71be05c8ae73ebb65b2270714c4e386e25975a08d33728183e1f212cdd2dd2404646e12185e2be57570bf3a224
    depends_on:
      - pyo_db
