version: '2'
services:
  pyo_db:
    image: mysql:5.7.22
    ports:
      - "4000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: procesosyoperaciones
      MYSQL_USER: user
      MYSQL_PASSWORD: procesosyoperaciones
      MYSQL_DATABASE: ProcesosOperaciones_production
      MYSQL_HOST: pyo_db
  pyo_ms:
    build: .
    command: bash -c "sleep 10 && rm -f tmp/pids/server.pid && bundle exec rails s -e production -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY_BASE: 248fb0e32fabd5b72e34ccb7d3a52c656c6bc361465b6f6176dd2b2724ef6d58dd47a2590458fd0fc7d2fc7ffb860f1020eb6d5d5103171b23a29b83a2ba14be
    depends_on:
      - pyo_db
