# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Departament.create([
  {name:'AMAZONAS', code: '91'},
  {name:'ANTIOQUIA', code: '05'},
  {name:'ARAUCA', code: '81'},
  {name:'ATLANTICO', code: '08'},
  {name:'BOGOTA', code: '11'},
  {name:'BOLIVAR', code: '13'},
  {name:'BOYACA', code: '15'},
  {name:'CALDAS', code: '17'},
  {name:'CAQUETA', code: '18'},
  {name:'CASANARE', code: '85'},
  {name:'CAUCA', code: '19'},
  {name:'CESAR', code: '20'},
  {name:'CHOCO', code: '27'},
  {name:'CORDOBA', code: '23'},
  {name:'CUNDINAMARCA', code: '25'},
  {name:'GUAINIA', code: '94'},
  {name:'GUAVIARE', code: '95'},
  {name:'HUILA', code: '41'},
  {name:'LA GUAJIRA', code: '44'},
  {name:'MAGDALENA', code: '47'},
  {name:'META', code: '50'},
  {name:'NARINO', code: '52'},
  {name:'NORTE DE SANTANDER', code: '54'},
  {name:'PUTUMAYO', code: '86'},
  {name:'QUINDIO', code: '63'},
  {name:'RISARALDA', code: '66'},
  {name:'SAN ANDRES', code: '88'},
  {name:'SANTANDER', code: '68'},
  {name:'SUCRE', code: '70'},
  {name:'TOLIMA', code: '73'},
  {name:'VALLE', code: '76'},
  {name:'VAUPES', code: '97'},
  {name:'VICHADA', code: '99'}
])

City.create([
  {name:'PUERTO SANTANDER', code: '669', departaments_id: 1},
  {name:'PUERTO ALEGRIA', code: '530', departaments_id: 1},
  {name:'EL ENCANTO', code: '263', departaments_id: 1},
  {name:'LA CHORRERA', code: '405', departaments_id: 1},
  {name:'TARAPACA', code: '798', departaments_id: 1},
  {name:'PUERTO NARINO', code: '540', departaments_id: 1},
  {name:'LETICIA', code: '001', departaments_id: 1},
  {name:'LA VICTORIA', code: '430', departaments_id: 1},
  {name:'MIRITI - PARANA', code: '460', departaments_id: 1},
  {name:'LA PEDRERA', code: '407', departaments_id: 1},
  {name:'PUERTO ARICA', code: '536', departaments_id: 1},
  {name:'SAN CARLOS', code: '649', departaments_id: 2},
  {name:'BETULIA', code: '093', departaments_id: 2},
  {name:'ANGOSTURA', code: '038', departaments_id: 2},
  {name:'SAN JOSE DE LA MONTANA', code: '658', departaments_id: 2},
  {name:'VALPARAISO', code: '856', departaments_id: 2},
  {name:'BELLO', code: '088', departaments_id: 2},
  {name:'GUATAPE', code: '321', departaments_id: 2},
  {name:'CANASGORDAS', code: '138', departaments_id: 2},
  {name:'CARACOLI', code: '142', departaments_id: 2},
  {name:'BARBOSA', code: '079', departaments_id: 2},
  {name:'SAN VICENTE', code: '674', departaments_id: 2},
  {name:'EBEJICO', code: '240', departaments_id: 2},
  {name:'SAN ANDRES DE CUERQUIA', code: '647', departaments_id: 2},
  {name:'TAMESIS', code: '789', departaments_id: 2},
  {name:'COCORNA', code: '197', departaments_id: 2},
  {name:'CONCORDIA', code: '209', departaments_id: 2},
  {name:'GIRARDOTA', code: '308', departaments_id: 2},
  {name:'CONCEPCION', code: '206', departaments_id: 2},
  {name:'SAN ROQUE', code: '670', departaments_id: 2},
  {name:'LA UNION', code: '400', departaments_id: 2},
  {name:'SANTA BARBARA', code: '679', departaments_id: 2},
  {name:'SABANALARGA', code: '628', departaments_id: 2},
  {name:'MUTATA', code: '480', departaments_id: 2},
  {name:'LA CEJA', code: '376', departaments_id: 2},
  {name:'SAN JUAN DE URABA', code: '659', departaments_id: 2},
  {name:'HISPANIA', code: '353', departaments_id: 2},
  {name:'SALGAR', code: '642', departaments_id: 2},
  {name:'SONSON', code: '756', departaments_id: 2},
  {name:'GIRALDO', code: '306', departaments_id: 2},
  {name:'ANGELOPOLIS', code: '036', departaments_id: 2},
  {name:'CIUDAD BOLIVAR', code: '101', departaments_id: 2},
  {name:'VIGIA DEL FUERTE', code: '873', departaments_id: 2},
  {name:'CISNEROS', code: '190', departaments_id: 2},
  {name:'SANTA ROSA DE OSOS', code: '686', departaments_id: 2},
  {name:'AMALFI', code: '031', departaments_id: 2},
  {name:'ANZA', code: '044', departaments_id: 2},
  {name:'TARSO', code: '792', departaments_id: 2},
  {name:'ARMENIA', code: '059', departaments_id: 2},
  {name:'TOLEDO', code: '819', departaments_id: 2},
  {name:'CAICEDO', code: '125', departaments_id: 2},
  {name:'BRICENO', code: '107', departaments_id: 2},
  {name:'JERICO', code: '368', departaments_id: 2},
  {name:'ZARAGOZA', code: '895', departaments_id: 2},
  {name:'HELICONIA', code: '347', departaments_id: 2},
  {name:'RIONEGRO', code: '615', departaments_id: 2},
  {name:'REMEDIOS', code: '604', departaments_id: 2},
  {name:'NECOCLI', code: '490', departaments_id: 2},
  {name:'TURBO', code: '837', departaments_id: 2},
  {name:'PUERTO TRIUNFO', code: '591', departaments_id: 2},
  {name:'URRAO', code: '847', departaments_id: 2},
  {name:'SAN LUIS', code: '660', departaments_id: 2},
  {name:'OLAYA', code: '501', departaments_id: 2},
  {name:'SAN JERONIMO', code: '656', departaments_id: 2},
  {name:'URAMITA', code: '842', departaments_id: 2},
  {name:'SABANETA', code: '631', departaments_id: 2},
  {name:'ANDES', code: '034', departaments_id: 2},
  {name:'NARINO', code: '483', departaments_id: 2},
  {name:'JARDIN', code: '364', departaments_id: 2},
  {name:'EL SANTUARIO', code: '697', departaments_id: 2},
  {name:'SAN PEDRO DE LOS MILAGROS', code: '664', departaments_id: 2},
  {name:'PUERTO BERRIO', code: '579', departaments_id: 2},
  {name:'CACERES', code: '120', departaments_id: 2},
  {name:'BELMIRA', code: '086', departaments_id: 2},
  {name:'PEQUE', code: '543', departaments_id: 2},
  {name:'COPACABANA', code: '212', departaments_id: 2},
  {name:'ABRIAQUI', code: '004', departaments_id: 2},
  {name:'BETANIA', code: '091', departaments_id: 2},
  {name:'LIBORINA', code: '411', departaments_id: 2},
  {name:'MEDELLIN', code: '001', departaments_id: 2},
  {name:'PUERTO NARE', code: '585', departaments_id: 2},
  {name:'YOLOMBO', code: '890', departaments_id: 2},
  {name:'CAMPAMENTO', code: '134', departaments_id: 2},
  {name:'DABEIBA', code: '234', departaments_id: 2},
  {name:'GUARNE', code: '318', departaments_id: 2},
  {name:'SOPETRAN', code: '761', departaments_id: 2},
  {name:'ITUANGO', code: '361', departaments_id: 2},
  {name:'RETIRO', code: '607', departaments_id: 2},
  {name:'FREDONIA', code: '282', departaments_id: 2},
  {name:'MACEO', code: '425', departaments_id: 2},
  {name:'YONDO', code: '893', departaments_id: 2},
  {name:'ARBOLETES', code: '051', departaments_id: 2},
  {name:'SAN RAFAEL', code: '667', departaments_id: 2},
  {name:'GUADALUPE', code: '315', departaments_id: 2},
  {name:'AMAGA', code: '030', departaments_id: 2},
  {name:'ENTRERRIOS', code: '264', departaments_id: 2},
  {name:'SEGOVIA', code: '736', departaments_id: 2},
  {name:'GOMEZ PLATA', code: '310', departaments_id: 2},
  {name:'YALI', code: '885', departaments_id: 2},
  {name:'SAN PEDRO DE URABA', code: '665', departaments_id: 2},
  {name:'NECHI', code: '495', departaments_id: 2},
  {name:'CALDAS', code: '129', departaments_id: 2},
  {name:'ANORI', code: '040', departaments_id: 2},
  {name:'TITIRIBI', code: '809', departaments_id: 2},
  {name:'TARAZA', code: '790', departaments_id: 2},
  {name:'ABEJORRAL', code: '002', departaments_id: 2},
  {name:'MARINILLA', code: '440', departaments_id: 2},
  {name:'EL CARMEN DE VIBORAL', code: '148', departaments_id: 2},
  {name:'LA ESTRELLA', code: '380', departaments_id: 2},
  {name:'VALDIVIA', code: '854', departaments_id: 2},
  {name:'CARAMANTA', code: '145', departaments_id: 2},
  {name:'PENOL', code: '541', departaments_id: 2},
  {name:'CAREPA', code: '147', departaments_id: 2},
  {name:'GRANADA', code: '313', departaments_id: 2},
  {name:'VENECIA', code: '861', departaments_id: 2},
  {name:'FRONTINO', code: '284', departaments_id: 2},
  {name:'APARTADO', code: '045', departaments_id: 2},
  {name:'DONMATIAS', code: '237', departaments_id: 2},
  {name:'ITAGUI', code: '360', departaments_id: 2},
  {name:'SANTAFE DE ANTIOQUIA', code: '042', departaments_id: 2},
  {name:'MONTEBELLO', code: '467', departaments_id: 2},
  {name:'CHIGORODO', code: '172', departaments_id: 2},
  {name:'BURITICA', code: '113', departaments_id: 2},
  {name:'ARGELIA', code: '055', departaments_id: 2},
  {name:'CAUCASIA', code: '154', departaments_id: 2},
  {name:'SAN FRANCISCO', code: '652', departaments_id: 2},
  {name:'YARUMAL', code: '887', departaments_id: 2},
  {name:'MURINDO', code: '475', departaments_id: 2},
  {name:'VEGACHI', code: '858', departaments_id: 2},
  {name:'PUEBLORRICO', code: '576', departaments_id: 2},
  {name:'LA PINTADA', code: '390', departaments_id: 2},
  {name:'EL BAGRE', code: '250', departaments_id: 2},
  {name:'ENVIGADO', code: '266', departaments_id: 2},
  {name:'SANTO DOMINGO', code: '690', departaments_id: 2},
  {name:'ALEJANDRIA', code: '021', departaments_id: 2},
  {name:'CAROLINA', code: '150', departaments_id: 2},
  {name:'ARAUQUITA', code: '065', departaments_id: 3},
  {name:'FORTUL', code: '300', departaments_id: 3},
  {name:'PUERTO RONDON', code: '591', departaments_id: 3},
  {name:'TAME', code: '794', departaments_id: 3},
  {name:'ARAUCA', code: '001', departaments_id: 3},
  {name:'CRAVO NORTE', code: '220', departaments_id: 3},
  {name:'SARAVENA', code: '736', departaments_id: 3},
  {name:'USIACURI', code: '849', departaments_id: 4},
  {name:'TUBARA', code: '832', departaments_id: 4},
  {name:'SUAN', code: '770', departaments_id: 4},
  {name:'GALAPA', code: '296', departaments_id: 4},
  {name:'BARRANQUILLA', code: '001', departaments_id: 4},
  {name:'JUAN DE ACOSTA', code: '372', departaments_id: 4},
  {name:'MALAMBO', code: '433', departaments_id: 4},
  {name:'MANATI', code: '436', departaments_id: 4},
  {name:'SABANAGRANDE', code: '634', departaments_id: 4},
  {name:'PIOJO', code: '549', departaments_id: 4},
  {name:'CAMPO DE LA CRUZ', code: '137', departaments_id: 4},
  {name:'SABANALARGA', code: '638', departaments_id: 4},
  {name:'BARANOA', code: '078', departaments_id: 4},
  {name:'POLONUEVO', code: '558', departaments_id: 4},
  {name:'LURUACO', code: '421', departaments_id: 4},
  {name:'REPELON', code: '606', departaments_id: 4},
  {name:'CANDELARIA', code: '141', departaments_id: 4},
  {name:'SANTO TOMAS', code: '685', departaments_id: 4},
  {name:'SANTA LUCIA', code: '675', departaments_id: 4},
  {name:'PUERTO COLOMBIA', code: '573', departaments_id: 4},
  {name:'SOLEDAD', code: '758', departaments_id: 4},
  {name:'PONEDERA', code: '560', departaments_id: 4},
  {name:'PALMAR DE VARELA', code: '520', departaments_id: 4},
  {name:'BOGOTA DC', code: '001', departaments_id: 5},
  {name:'SANTA CATALINA', code: '673', departaments_id: 6},
  {name:'ZAMBRANO', code: '894', departaments_id: 6},
  {name:'SAN PABLO', code: '670', departaments_id: 6},
  {name:'SAN MARTIN DE LOBA', code: '667', departaments_id: 6},
  {name:'EL CARMEN DE BOLIVAR', code: '244', departaments_id: 6},
  {name:'BARRANCO DE LOBA', code: '074', departaments_id: 6},
  {name:'SIMITI', code: '744', departaments_id: 6},
  {name:'TIQUISIO', code: '810', departaments_id: 6},
  {name:'SAN JUAN NEPOMUCENO', code: '657', departaments_id: 6},
  {name:'SANTA ROSA DEL SUR', code: '688', departaments_id: 6},
  {name:'NOROSI', code: '490', departaments_id: 6},
  {name:'CARTAGENA', code: '001', departaments_id: 6},
  {name:'CICUCO', code: '188', departaments_id: 6},
  {name:'MONTECRISTO', code: '458', departaments_id: 6},
  {name:'VILLANUEVA', code: '873', departaments_id: 6},
  {name:'ACHI', code: '006', departaments_id: 6},
  {name:'MORALES', code: '473', departaments_id: 6},
  {name:'PINILLOS', code: '549', departaments_id: 6},
  {name:'HATILLO DE LOBA', code: '300', departaments_id: 6},
  {name:'RIO VIEJO', code: '600', departaments_id: 6},
  {name:'MOMPOS', code: '468', departaments_id: 6},
  {name:'MAHATES', code: '433', departaments_id: 6},
  {name:'SANTA ROSA', code: '683', departaments_id: 6},
  {name:'TALAIGUA NUEVO', code: '780', departaments_id: 6},
  {name:'ARROYOHONDO', code: '062', departaments_id: 6},
  {name:'SAN JACINTO DEL CAUCA', code: '655', departaments_id: 6},
  {name:'SAN CRISTOBAL', code: '620', departaments_id: 6},
  {name:'CALAMAR', code: '140', departaments_id: 6},
  {name:'SAN JACINTO', code: '654', departaments_id: 6},
  {name:'MARIA LA BAJA', code: '442', departaments_id: 6},
  {name:'MAGANGUE', code: '430', departaments_id: 6},
  {name:'CORDOBA', code: '212', departaments_id: 6},
  {name:'SOPLAVIENTO', code: '760', departaments_id: 6},
  {name:'TURBACO', code: '836', departaments_id: 6},
  {name:'CANTAGALLO', code: '160', departaments_id: 6},
  {name:'ARENAL', code: '042', departaments_id: 6},
  {name:'EL GUAMO', code: '248', departaments_id: 6},
  {name:'SAN FERNANDO', code: '650', departaments_id: 6},
  {name:'ALTOS DEL ROSARIO', code: '030', departaments_id: 6},
  {name:'TURBANA', code: '838', departaments_id: 6},
  {name:'EL PENON', code: '268', departaments_id: 6},
  {name:'ARJONA', code: '052', departaments_id: 6},
  {name:'CLEMENCIA', code: '222', departaments_id: 6},
  {name:'SAN ESTANISLAO', code: '647', departaments_id: 6},
  {name:'REGIDOR', code: '580', departaments_id: 6},
  {name:'MARGARITA', code: '440', departaments_id: 6},
  {name:'VENTAQUEMADA', code: '861', departaments_id: 7},
  {name:'ZETAQUIRA', code: '897', departaments_id: 7},
  {name:'TOPAGA', code: '820', departaments_id: 7},
  {name:'CORRALES', code: '215', departaments_id: 7},
  {name:'TENZA', code: '798', departaments_id: 7},
  {name:'TURMEQUE', code: '835', departaments_id: 7},
  {name:'MONGUA', code: '464', departaments_id: 7},
  {name:'FIRAVITOBA', code: '272', departaments_id: 7},
  {name:'GUAYATA', code: '325', departaments_id: 7},
  {name:'MACANAL', code: '425', departaments_id: 7},
  {name:'EL COCUY', code: '244', departaments_id: 7},
  {name:'SANTA SOFIA', code: '696', departaments_id: 7},
  {name:'VILLA DE LEYVA', code: '407', departaments_id: 7},
  {name:'CUITIVA', code: '226', departaments_id: 7},
  {name:'TUTA', code: '837', departaments_id: 7},
  {name:'SOGAMOSO', code: '759', departaments_id: 7},
  {name:'BELEN', code: '087', departaments_id: 7},
  {name:'OICATA', code: '500', departaments_id: 7},
  {name:'CHIVATA', code: '187', departaments_id: 7},
  {name:'COPER', code: '212', departaments_id: 7},
  {name:'LA VICTORIA', code: '401', departaments_id: 7},
  {name:'MUZO', code: '480', departaments_id: 7},
  {name:'TIBASOSA', code: '806', departaments_id: 7},
  {name:'JENESANO', code: '367', departaments_id: 7},
  {name:'BRICENO', code: '106', departaments_id: 7},
  {name:'JERICO', code: '368', departaments_id: 7},
  {name:'QUIPAMA', code: '580', departaments_id: 7},
  {name:'LABRANZAGRANDE', code: '377', departaments_id: 7},
  {name:'SORACA', code: '764', departaments_id: 7},
  {name:'CHISCAS', code: '180', departaments_id: 7},
  {name:'TUNUNGUA', code: '832', departaments_id: 7},
  {name:'PANQUEBA', code: '522', departaments_id: 7},
  {name:'TIBANA', code: '804', departaments_id: 7},
  {name:'PAJARITO', code: '518', departaments_id: 7},
  {name:'PUERTO BOYACA', code: '572', departaments_id: 7},
  {name:'SOTAQUIRA', code: '763', departaments_id: 7},
  {name:'PESCA', code: '542', departaments_id: 7},
  {name:'BOYACA', code: '104', departaments_id: 7},
  {name:'MONGUI', code: '466', departaments_id: 7},
  {name:'CAMPOHERMOSO', code: '135', departaments_id: 7},
  {name:'COVARACHIA', code: '218', departaments_id: 7},
  {name:'SUTAMARCHAN', code: '776', departaments_id: 7},
  {name:'SAN MIGUEL DE SEMA', code: '676', departaments_id: 7},
  {name:'AQUITANIA', code: '047', departaments_id: 7},
  {name:'PAUNA', code: '531', departaments_id: 7},
  {name:'TIPACOQUE', code: '810', departaments_id: 7},
  {name:'LA CAPILLA', code: '380', departaments_id: 7},
  {name:'SABOYA', code: '632', departaments_id: 7},
  {name:'PAYA', code: '533', departaments_id: 7},
  {name:'ALMEIDA', code: '022', departaments_id: 7},
  {name:'CHITARAQUE', code: '185', departaments_id: 7},
  {name:'TUNJA', code: '001', departaments_id: 7},
  {name:'TUTAZA', code: '839', departaments_id: 7},
  {name:'SAN JOSE DE PARE', code: '664', departaments_id: 7},
  {name:'MOTAVITA', code: '476', departaments_id: 7},
  {name:'BUENAVISTA', code: '109', departaments_id: 7},
  {name:'TASCO', code: '790', departaments_id: 7},
  {name:'TOCA', code: '814', departaments_id: 7},
  {name:'MARIPI', code: '442', departaments_id: 7},
  {name:'OTANCHE', code: '507', departaments_id: 7},
  {name:'CUCAITA', code: '224', departaments_id: 7},
  {name:'SAMACA', code: '646', departaments_id: 7},
  {name:'SATIVANORTE', code: '720', departaments_id: 7},
  {name:'PAIPA', code: '516', departaments_id: 7},
  {name:'RONDON', code: '621', departaments_id: 7},
  {name:'BUSBANZA', code: '114', departaments_id: 7},
  {name:'SAN EDUARDO', code: '660', departaments_id: 7},
  {name:'BERBEO', code: '090', departaments_id: 7},
  {name:'SANTA ROSA DE VITERBO', code: '693', departaments_id: 7},
  {name:'SANTANA', code: '686', departaments_id: 7},
  {name:'GACHANTIVA', code: '293', departaments_id: 7},
  {name:'SOCHA', code: '757', departaments_id: 7},
  {name:'PAZ DE RIO', code: '537', departaments_id: 7},
  {name:'SIACHOQUE', code: '740', departaments_id: 7},
  {name:'BETEITIVA', code: '092', departaments_id: 7},
  {name:'SORA', code: '762', departaments_id: 7},
  {name:'SACHICA', code: '638', departaments_id: 7},
  {name:'CHINAVITA', code: '172', departaments_id: 7},
  {name:'CERINZA', code: '162', departaments_id: 7},
  {name:'UMBITA', code: '842', departaments_id: 7},
  {name:'NUEVO COLON', code: '494', departaments_id: 7},
  {name:'CALDAS', code: '131', departaments_id: 7},
  {name:'GARAGOA', code: '299', departaments_id: 7},
  {name:'PACHAVITA', code: '511', departaments_id: 7},
  {name:'SOATA', code: '753', departaments_id: 7},
  {name:'SOCOTA', code: '755', departaments_id: 7},
  {name:'CIENEGA', code: '189', departaments_id: 7},
  {name:'PISBA', code: '550', departaments_id: 7},
  {name:'GUACAMAYAS', code: '317', departaments_id: 7},
  {name:'EL ESPINO', code: '248', departaments_id: 7},
  {name:'MIRAFLORES', code: '455', departaments_id: 7},
  {name:'GAMEZA', code: '296', departaments_id: 7},
  {name:'SAN PABLO DE BORBUR', code: '681', departaments_id: 7},
  {name:'CHIVOR', code: '236', departaments_id: 7},
  {name:'GUICAN', code: '332', departaments_id: 7},
  {name:'CUBARA', code: '223', departaments_id: 7},
  {name:'SAN LUIS DE GACENO', code: '667', departaments_id: 7},
  {name:'PAEZ', code: '514', departaments_id: 7},
  {name:'SAN MATEO', code: '673', departaments_id: 7},
  {name:'TOGUI', code: '816', departaments_id: 7},
  {name:'CHIQUIZA', code: '232', departaments_id: 7},
  {name:'RAMIRIQUI', code: '599', departaments_id: 7},
  {name:'RAQUIRA', code: '600', departaments_id: 7},
  {name:'LA UVITA', code: '403', departaments_id: 7},
  {name:'SUSACON', code: '774', departaments_id: 7},
  {name:'TINJACA', code: '808', departaments_id: 7},
  {name:'NOBSA', code: '491', departaments_id: 7},
  {name:'GUATEQUE', code: '322', departaments_id: 7},
  {name:'IZA', code: '362', departaments_id: 7},
  {name:'BOAVITA', code: '097', departaments_id: 7},
  {name:'SOMONDOCO', code: '761', departaments_id: 7},
  {name:'FLORESTA', code: '276', departaments_id: 7},
  {name:'TOTA', code: '822', departaments_id: 7},
  {name:'CHITA', code: '183', departaments_id: 7},
  {name:'SUTATENZA', code: '778', departaments_id: 7},
  {name:'SATIVASUR', code: '723', departaments_id: 7},
  {name:'VIRACACHA', code: '879', departaments_id: 7},
  {name:'CHIQUINQUIRA', code: '176', departaments_id: 7},
  {name:'MONIQUIRA', code: '469', departaments_id: 7},
  {name:'SANTA MARIA', code: '690', departaments_id: 7},
  {name:'ARCABUCO', code: '051', departaments_id: 7},
  {name:'DUITAMA', code: '238', departaments_id: 7},
  {name:'COMBITA', code: '204', departaments_id: 7},
  {name:'NORCASIA', code: '495', departaments_id: 8},
  {name:'MANIZALES', code: '001', departaments_id: 8},
  {name:'RIOSUCIO', code: '614', departaments_id: 8},
  {name:'MARQUETALIA', code: '444', departaments_id: 8},
  {name:'SUPIA', code: '777', departaments_id: 8},
  {name:'CHINCHINA', code: '174', departaments_id: 8},
  {name:'MANZANARES', code: '433', departaments_id: 8},
  {name:'AGUADAS', code: '013', departaments_id: 8},
  {name:'PACORA', code: '513', departaments_id: 8},
  {name:'LA MERCED', code: '388', departaments_id: 8},
  {name:'LA DORADA', code: '380', departaments_id: 8},
  {name:'VITERBO', code: '877', departaments_id: 8},
  {name:'SAMANA', code: '662', departaments_id: 8},
  {name:'VICTORIA', code: '867', departaments_id: 8},
  {name:'RISARALDA', code: '616', departaments_id: 8},
  {name:'FILADELFIA', code: '272', departaments_id: 8},
  {name:'ANSERMA', code: '042', departaments_id: 8},
  {name:'BELALCAZAR', code: '088', departaments_id: 8},
  {name:'MARMATO', code: '442', departaments_id: 8},
  {name:'PENSILVANIA', code: '541', departaments_id: 8},
  {name:'PALESTINA', code: '524', departaments_id: 8},
  {name:'NEIRA', code: '486', departaments_id: 8},
  {name:'ARANZAZU', code: '050', departaments_id: 8},
  {name:'VILLAMARIA', code: '873', departaments_id: 8},
  {name:'MARULANDA', code: '446', departaments_id: 8},
  {name:'SAN JOSE', code: '665', departaments_id: 8},
  {name:'SALAMINA', code: '653', departaments_id: 8},
  {name:'FLORENCIA', code: '001', departaments_id: 9},
  {name:'EL DONCELLO', code: '247', departaments_id: 9},
  {name:'SAN VICENTE DEL CAGUAN', code: '753', departaments_id: 9},
  {name:'ALBANIA', code: '029', departaments_id: 9},
  {name:'SOLANO', code: '756', departaments_id: 9},
  {name:'EL PAUJIL', code: '256', departaments_id: 9},
  {name:'CARTAGENA DEL CHAIRA', code: '150', departaments_id: 9},
  {name:'VALPARAISO', code: '860', departaments_id: 9},
  {name:'BELEN DE LOS ANDAQUIES', code: '094', departaments_id: 9},
  {name:'SOLITA', code: '785', departaments_id: 9},
  {name:'MILAN', code: '460', departaments_id: 9},
  {name:'LA MONTANITA', code: '410', departaments_id: 9},
  {name:'PUERTO RICO', code: '592', departaments_id: 9},
  {name:'CURILLO', code: '205', departaments_id: 9},
  {name:'MORELIA', code: '479', departaments_id: 9},
  {name:'SAN JOSE DEL FRAGUA', code: '610', departaments_id: 9},
  {name:'AGUAZUL', code: '010', departaments_id: 10},
  {name:'MONTERREY', code: '162', departaments_id: 10},
  {name:'HATO COROZAL', code: '125', departaments_id: 10},
  {name:'CHAMEZA', code: '015', departaments_id: 10},
  {name:'RECETOR', code: '279', departaments_id: 10},
  {name:'PORE', code: '263', departaments_id: 10},
  {name:'SABANALARGA', code: '300', departaments_id: 10},
  {name:'SAN LUIS DE PALENQUE', code: '325', departaments_id: 10},
  {name:'VILLANUEVA', code: '440', departaments_id: 10},
  {name:'LA SALINA', code: '136', departaments_id: 10},
  {name:'MANI', code: '139', departaments_id: 10},
  {name:'YOPAL', code: '001', departaments_id: 10},
  {name:'NUNCHIA', code: '225', departaments_id: 10},
  {name:'SACAMA', code: '315', departaments_id: 10},
  {name:'TAMARA', code: '400', departaments_id: 10},
  {name:'TRINIDAD', code: '430', departaments_id: 10},
  {name:'PAZ DE ARIPORO', code: '250', departaments_id: 10},
  {name:'OROCUE', code: '230', departaments_id: 10},
  {name:'TAURAMENA', code: '410', departaments_id: 10},
  {name:'FLORENCIA', code: '290', departaments_id: 11},
  {name:'TIMBIO', code: '807', departaments_id: 11},
  {name:'GUACHENE', code: '300', departaments_id: 11},
  {name:'LA SIERRA', code: '392', departaments_id: 11},
  {name:'CORINTO', code: '212', departaments_id: 11},
  {name:'TOTORO', code: '824', departaments_id: 11},
  {name:'BUENOS AIRES', code: '110', departaments_id: 11},
  {name:'SANTA ROSA', code: '701', departaments_id: 11},
  {name:'POPAYAN', code: '001', departaments_id: 11},
  {name:'SANTANDER DE QUILICHAO', code: '698', departaments_id: 11},
  {name:'ARGELIA', code: '050', departaments_id: 11},
  {name:'JAMBALO', code: '364', departaments_id: 11},
  {name:'CAJIBIO', code: '130', departaments_id: 11},
  {name:'SUCRE', code: '785', departaments_id: 11},
  {name:'MORALES', code: '473', departaments_id: 11},
  {name:'LA VEGA', code: '397', departaments_id: 11},
  {name:'PADILLA', code: '513', departaments_id: 11},
  {name:'LOPEZ', code: '418', departaments_id: 11},
  {name:'PAEZ', code: '517', departaments_id: 11},
  {name:'PIAMONTE', code: '533', departaments_id: 11},
  {name:'SUAREZ', code: '780', departaments_id: 11},
  {name:'PURACE', code: '585', departaments_id: 11},
  {name:'BOLIVAR', code: '100', departaments_id: 11},
  {name:'PUERTO TEJADA', code: '573', departaments_id: 11},
  {name:'ALMAGUER', code: '022', departaments_id: 11},
  {name:'PIENDAMO', code: '548', departaments_id: 11},
  {name:'TIMBIQUI', code: '809', departaments_id: 11},
  {name:'INZA', code: '355', departaments_id: 11},
  {name:'EL TAMBO', code: '256', departaments_id: 11},
  {name:'ROSAS', code: '622', departaments_id: 11},
  {name:'CALOTO', code: '142', departaments_id: 11},
  {name:'SAN SEBASTIAN', code: '693', departaments_id: 11},
  {name:'VILLA RICA', code: '845', departaments_id: 11},
  {name:'PATIA', code: '532', departaments_id: 11},
  {name:'SILVIA', code: '743', departaments_id: 11},
  {name:'GUAPI', code: '318', departaments_id: 11},
  {name:'SOTARA', code: '760', departaments_id: 11},
  {name:'MIRANDA', code: '455', departaments_id: 11},
  {name:'CALDONO', code: '137', departaments_id: 11},
  {name:'BALBOA', code: '075', departaments_id: 11},
  {name:'TORIBIO', code: '821', departaments_id: 11},
  {name:'MERCADERES', code: '450', departaments_id: 11},
  {name:'LA GLORIA', code: '383', departaments_id: 12},
  {name:'SAN ALBERTO', code: '710', departaments_id: 12},
  {name:'AGUSTIN CODAZZI', code: '013', departaments_id: 12},
  {name:'CHIRIGUANA', code: '178', departaments_id: 12},
  {name:'MANAURE', code: '443', departaments_id: 12},
  {name:'TAMALAMEQUE', code: '787', departaments_id: 12},
  {name:'SAN DIEGO', code: '750', departaments_id: 12},
  {name:'EL COPEY', code: '238', departaments_id: 12},
  {name:'EL PASO', code: '250', departaments_id: 12},
  {name:'LA JAGUA DE IBIRICO', code: '400', departaments_id: 12},
  {name:'RIO DE ORO', code: '614', departaments_id: 12},
  {name:'GAMARRA', code: '295', departaments_id: 12},
  {name:'CURUMANI', code: '228', departaments_id: 12},
  {name:'PUEBLO BELLO', code: '570', departaments_id: 12},
  {name:'BECERRIL', code: '045', departaments_id: 12},
  {name:'PELAYA', code: '550', departaments_id: 12},
  {name:'BOSCONIA', code: '060', departaments_id: 12},
  {name:'CHIMICHAGUA', code: '175', departaments_id: 12},
  {name:'VALLEDUPAR', code: '001', departaments_id: 12},
  {name:'GONZALEZ', code: '310', departaments_id: 12},
  {name:'PAILITAS', code: '517', departaments_id: 12},
  {name:'AGUACHICA', code: '011', departaments_id: 12},
  {name:'SAN MARTIN', code: '770', departaments_id: 12},
  {name:'ASTREA', code: '032', departaments_id: 12},
  {name:'LA PAZ', code: '621', departaments_id: 12},
  {name:'ATRATO', code: '050', departaments_id: 13},
  {name:'CERTEGUI', code: '160', departaments_id: 13},
  {name:'RIOSUCIO', code: '615', departaments_id: 13},
  {name:'NOVITA', code: '491', departaments_id: 13},
  {name:'TADO', code: '787', departaments_id: 13},
  {name:'EL CARMEN DE ATRATO', code: '245', departaments_id: 13},
  {name:'EL CANTON DEL SAN PABLO', code: '135', departaments_id: 13},
  {name:'QUIBDO', code: '001', departaments_id: 13},
  {name:'CARMEN DEL DARIEN', code: '150', departaments_id: 13},
  {name:'MEDIO ATRATO', code: '425', departaments_id: 13},
  {name:'BAGADO', code: '073', departaments_id: 13},
  {name:'LLORO', code: '413', departaments_id: 13},
  {name:'CONDOTO', code: '205', departaments_id: 13},
  {name:'RIO QUITO', code: '600', departaments_id: 13},
  {name:'SIPI', code: '745', departaments_id: 13},
  {name:'ISTMINA', code: '361', departaments_id: 13},
  {name:'UNION PANAMERICANA', code: '810', departaments_id: 13},
  {name:'BAJO BAUDO', code: '077', departaments_id: 13},
  {name:'SAN JOSE DEL PALMAR', code: '660', departaments_id: 13},
  {name:'ALTO BAUDO', code: '025', departaments_id: 13},
  {name:'MEDIO BAUDO', code: '430', departaments_id: 13},
  {name:'ACANDI', code: '006', departaments_id: 13},
  {name:'UNGUIA', code: '800', departaments_id: 13},
  {name:'MEDIO SAN JUAN', code: '450', departaments_id: 13},
  {name:'BOJAYA', code: '099', departaments_id: 13},
  {name:'JURADO', code: '372', departaments_id: 13},
  {name:'EL LITORAL DEL SAN JUAN', code: '250', departaments_id: 13},
  {name:'RIO IRO', code: '580', departaments_id: 13},
  {name:'BAHIA SOLANO', code: '075', departaments_id: 13},
  {name:'NUQUI', code: '495', departaments_id: 13},
  {name:'SAN CARLOS', code: '678', departaments_id: 14},
  {name:'SAN BERNARDO DEL VIENTO', code: '675', departaments_id: 14},
  {name:'BUENAVISTA', code: '079', departaments_id: 14},
  {name:'LOS CORDOBAS', code: '419', departaments_id: 14},
  {name:'CIENAGA DE ORO', code: '189', departaments_id: 14},
  {name:'PUERTO ESCONDIDO', code: '574', departaments_id: 14},
  {name:'PLANETA RICA', code: '555', departaments_id: 14},
  {name:'CANALETE', code: '090', departaments_id: 14},
  {name:'AYAPEL', code: '068', departaments_id: 14},
  {name:'MONTELIBANO', code: '466', departaments_id: 14},
  {name:'SAN PELAYO', code: '686', departaments_id: 14},
  {name:'SAN ANTERO', code: '672', departaments_id: 14},
  {name:'SAN ANDRES SOTAVENTO', code: '670', departaments_id: 14},
  {name:'VALENCIA', code: '855', departaments_id: 14},
  {name:'CHIMA', code: '168', departaments_id: 14},
  {name:'CHINU', code: '182', departaments_id: 14},
  {name:'MONITOS', code: '500', departaments_id: 14},
  {name:'MOMIL', code: '464', departaments_id: 14},
  {name:'COTORRA', code: '300', departaments_id: 14},
  {name:'PUERTO LIBERTADOR', code: '580', departaments_id: 14},
  {name:'PURISIMA', code: '586', departaments_id: 14},
  {name:'CERETE', code: '162', departaments_id: 14},
  {name:'SAHAGUN', code: '660', departaments_id: 14},
  {name:'TIERRALTA', code: '807', departaments_id: 14},
  {name:'MONTERIA', code: '001', departaments_id: 14},
  {name:'TUCHIN', code: '815', departaments_id: 14},
  {name:'SAN JOSE DE URE', code: '682', departaments_id: 14},
  {name:'LA APARTADA', code: '350', departaments_id: 14},
  {name:'PUEBLO NUEVO', code: '570', departaments_id: 14},
  {name:'LORICA', code: '417', departaments_id: 14},
  {name:'SILVANIA', code: '743', departaments_id: 15},
  {name:'NEMOCON', code: '486', departaments_id: 15},
  {name:'TABIO', code: '785', departaments_id: 15},
  {name:'PAIME', code: '518', departaments_id: 15},
  {name:'GUATAVITA', code: '326', departaments_id: 15},
  {name:'ANOLAIMA', code: '040', departaments_id: 15},
  {name:'FUSAGASUGA', code: '290', departaments_id: 15},
  {name:'ANAPOIMA', code: '035', departaments_id: 15},
  {name:'NILO', code: '488', departaments_id: 15},
  {name:'VILLAPINZON', code: '873', departaments_id: 15},
  {name:'SAN BERNARDO', code: '649', departaments_id: 15},
  {name:'VILLETA', code: '875', departaments_id: 15},
  {name:'QUETAME', code: '594', departaments_id: 15},
  {name:'PARATEBUENO', code: '530', departaments_id: 15},
  {name:'GUACHETA', code: '317', departaments_id: 15},
  {name:'AGUA DE DIOS', code: '001', departaments_id: 15},
  {name:'LA PENA', code: '398', departaments_id: 15},
  {name:'APULO', code: '599', departaments_id: 15},
  {name:'SASAIMA', code: '718', departaments_id: 15},
  {name:'UTICA', code: '851', departaments_id: 15},
  {name:'CACHIPAY', code: '123', departaments_id: 15},
  {name:'COGUA', code: '200', departaments_id: 15},
  {name:'TOCAIMA', code: '815', departaments_id: 15},
  {name:'SAN ANTONIO DEL TEQUENDAMA', code: '645', departaments_id: 15},
  {name:'SUTATAUSA', code: '781', departaments_id: 15},
  {name:'PANDI', code: '524', departaments_id: 15},
  {name:'QUEBRADANEGRA', code: '592', departaments_id: 15},
  {name:'JERUSALEN', code: '368', departaments_id: 15},
  {name:'MACHETA', code: '426', departaments_id: 15},
  {name:'CAQUEZA', code: '151', departaments_id: 15},
  {name:'VILLA DE SAN DIEGO DE UBATE', code: '843', departaments_id: 15},
  {name:'GUATAQUI', code: '324', departaments_id: 15},
  {name:'FOMEQUE', code: '279', departaments_id: 15},
  {name:'NOCAIMA', code: '491', departaments_id: 15},
  {name:'CHIA', code: '175', departaments_id: 15},
  {name:'PULI', code: '580', departaments_id: 15},
  {name:'SOACHA', code: '754', departaments_id: 15},
  {name:'FOSCA', code: '281', departaments_id: 15},
  {name:'CAPARRAPI', code: '148', departaments_id: 15},
  {name:'RICAURTE', code: '612', departaments_id: 15},
  {name:'GUAYABAL DE SIQUIMA', code: '328', departaments_id: 15},
  {name:'SAN CAYETANO', code: '653', departaments_id: 15},
  {name:'BITUIMA', code: '095', departaments_id: 15},
  {name:'CAJICA', code: '126', departaments_id: 15},
  {name:'LENGUAZAQUE', code: '407', departaments_id: 15},
  {name:'EL COLEGIO', code: '245', departaments_id: 15},
  {name:'NARINO', code: '483', departaments_id: 15},
  {name:'VILLAGOMEZ', code: '871', departaments_id: 15},
  {name:'CHOCONTA', code: '183', departaments_id: 15},
  {name:'GUTIERREZ', code: '339', departaments_id: 15},
  {name:'TOCANCIPA', code: '817', departaments_id: 15},
  {name:'MANTA', code: '436', departaments_id: 15},
  {name:'TIBACUY', code: '805', departaments_id: 15},
  {name:'CHIPAQUE', code: '178', departaments_id: 15},
  {name:'CABRERA', code: '120', departaments_id: 15},
  {name:'PUERTO SALGAR', code: '572', departaments_id: 15},
  {name:'UBAQUE', code: '841', departaments_id: 15},
  {name:'GUAYABETAL', code: '335', departaments_id: 15},
  {name:'TENA', code: '797', departaments_id: 15},
  {name:'SESQUILE', code: '736', departaments_id: 15},
  {name:'QUIPILE', code: '596', departaments_id: 15},
  {name:'GACHALA', code: '293', departaments_id: 15},
  {name:'YACOPI', code: '885', departaments_id: 15},
  {name:'GACHETA', code: '297', departaments_id: 15},
  {name:'MADRID', code: '430', departaments_id: 15},
  {name:'COTA', code: '214', departaments_id: 15},
  {name:'MOSQUERA', code: '473', departaments_id: 15},
  {name:'GAMA', code: '299', departaments_id: 15},
  {name:'TAUSA', code: '793', departaments_id: 15},
  {name:'LA PALMA', code: '394', departaments_id: 15},
  {name:'VIOTA', code: '878', departaments_id: 15},
  {name:'PACHO', code: '513', departaments_id: 15},
  {name:'SUPATA', code: '777', departaments_id: 15},
  {name:'EL PENON', code: '258', departaments_id: 15},
  {name:'LA MESA', code: '386', departaments_id: 15},
  {name:'GUASCA', code: '322', departaments_id: 15},
  {name:'SUSA', code: '779', departaments_id: 15},
  {name:'MEDINA', code: '438', departaments_id: 15},
  {name:'SIBATE', code: '740', departaments_id: 15},
  {name:'UNE', code: '845', departaments_id: 15},
  {name:'GUADUAS', code: '320', departaments_id: 15},
  {name:'SUESCA', code: '772', departaments_id: 15},
  {name:'SAN JUAN DE RIO SECO', code: '662', departaments_id: 15},
  {name:'FUNZA', code: '286', departaments_id: 15},
  {name:'CHOACHI', code: '181', departaments_id: 15},
  {name:'FUQUENE', code: '288', departaments_id: 15},
  {name:'BOJACA', code: '099', departaments_id: 15},
  {name:'SIMIJACA', code: '745', departaments_id: 15},
  {name:'SUBACHOQUE', code: '769', departaments_id: 15},
  {name:'ZIPAQUIRA', code: '899', departaments_id: 15},
  {name:'EL ROSAL', code: '260', departaments_id: 15},
  {name:'TOPAIPI', code: '823', departaments_id: 15},
  {name:'GRANADA', code: '312', departaments_id: 15},
  {name:'VIANI', code: '867', departaments_id: 15},
  {name:'BELTRAN', code: '086', departaments_id: 15},
  {name:'CHAGUANI', code: '168', departaments_id: 15},
  {name:'ZIPACON', code: '898', departaments_id: 15},
  {name:'LA VEGA', code: '402', departaments_id: 15},
  {name:'VENECIA', code: '506', departaments_id: 15},
  {name:'CARMEN DE CARUPA', code: '154', departaments_id: 15},
  {name:'VERGARA', code: '862', departaments_id: 15},
  {name:'CUCUNUBA', code: '224', departaments_id: 15},
  {name:'TENJO', code: '799', departaments_id: 15},
  {name:'ALBAN', code: '019', departaments_id: 15},
  {name:'NIMAIMA', code: '489', departaments_id: 15},
  {name:'JUNIN', code: '372', departaments_id: 15},
  {name:'PASCA', code: '535', departaments_id: 15},
  {name:'UBALA', code: '839', departaments_id: 15},
  {name:'SAN FRANCISCO', code: '658', departaments_id: 15},
  {name:'GIRARDOT', code: '307', departaments_id: 15},
  {name:'SOPO', code: '758', departaments_id: 15},
  {name:'ARBELAEZ', code: '053', departaments_id: 15},
  {name:'GACHANCIPA', code: '295', departaments_id: 15},
  {name:'FACATATIVA', code: '269', departaments_id: 15},
  {name:'LA CALERA', code: '377', departaments_id: 15},
  {name:'TIBIRITA', code: '807', departaments_id: 15},
  {name:'CACAHUAL', code: '886', departaments_id: 16},
  {name:'PANA PANA', code: '887', departaments_id: 16},
  {name:'MAPIRIPANA', code: '663', departaments_id: 16},
  {name:'MORICHAL', code: '888', departaments_id: 16},
  {name:'BARRANCO MINAS', code: '343', departaments_id: 16},
  {name:'INIRIDA', code: '001', departaments_id: 16},
  {name:'PUERTO COLOMBIA', code: '884', departaments_id: 16},
  {name:'LA GUADALUPE', code: '885', departaments_id: 16},
  {name:'SAN FELIPE', code: '883', departaments_id: 16},
  {name:'CALAMAR', code: '015', departaments_id: 17},
  {name:'EL RETORNO', code: '025', departaments_id: 17},
  {name:'SAN JOSE DEL GUAVIARE', code: '001', departaments_id: 17},
  {name:'MIRAFLORES', code: '200', departaments_id: 17},
  {name:'SAN AGUSTIN', code: '668', departaments_id: 18},
  {name:'PALERMO', code: '524', departaments_id: 18},
  {name:'TARQUI', code: '791', departaments_id: 18},
  {name:'HOBO', code: '349', departaments_id: 18},
  {name:'LA PLATA', code: '396', departaments_id: 18},
  {name:'TIMANA', code: '807', departaments_id: 18},
  {name:'NEIVA', code: '001', departaments_id: 18},
  {name:'CAMPOALEGRE', code: '132', departaments_id: 18},
  {name:'TESALIA', code: '797', departaments_id: 18},
  {name:'YAGUARA', code: '885', departaments_id: 18},
  {name:'OPORAPA', code: '503', departaments_id: 18},
  {name:'SALADOBLANCO', code: '660', departaments_id: 18},
  {name:'ELIAS', code: '244', departaments_id: 18},
  {name:'COLOMBIA', code: '206', departaments_id: 18},
  {name:'VILLAVIEJA', code: '872', departaments_id: 18},
  {name:'NATAGA', code: '483', departaments_id: 18},
  {name:'PALESTINA', code: '530', departaments_id: 18},
  {name:'RIVERA', code: '615', departaments_id: 18},
  {name:'ALGECIRAS', code: '020', departaments_id: 18},
  {name:'TELLO', code: '799', departaments_id: 18},
  {name:'ACEVEDO', code: '006', departaments_id: 18},
  {name:'PITALITO', code: '551', departaments_id: 18},
  {name:'GUADALUPE', code: '319', departaments_id: 18},
  {name:'BARAYA', code: '078', departaments_id: 18},
  {name:'AIPE', code: '016', departaments_id: 18},
  {name:'SANTA MARIA', code: '676', departaments_id: 18},
  {name:'LA ARGENTINA', code: '378', departaments_id: 18},
  {name:'ALTAMIRA', code: '026', departaments_id: 18},
  {name:'GIGANTE', code: '306', departaments_id: 18},
  {name:'ISNOS', code: '359', departaments_id: 18},
  {name:'PAICOL', code: '518', departaments_id: 18},
  {name:'GARZON', code: '298', departaments_id: 18},
  {name:'AGRADO', code: '013', departaments_id: 18},
  {name:'TERUEL', code: '801', departaments_id: 18},
  {name:'IQUIRA', code: '357', departaments_id: 18},
  {name:'SUAZA', code: '770', departaments_id: 18},
  {name:'PITAL', code: '548', departaments_id: 18},
  {name:'DIBULLA', code: '090', departaments_id: 19},
  {name:'DISTRACCION', code: '098', departaments_id: 19},
  {name:'SAN JUAN DEL CESAR', code: '650', departaments_id: 19},
  {name:'MAICAO', code: '430', departaments_id: 19},
  {name:'VILLANUEVA', code: '874', departaments_id: 19},
  {name:'URIBIA', code: '847', departaments_id: 19},
  {name:'BARRANCAS', code: '078', departaments_id: 19},
  {name:'ALBANIA', code: '035', departaments_id: 19},
  {name:'EL MOLINO', code: '110', departaments_id: 19},
  {name:'HATONUEVO', code: '378', departaments_id: 19},
  {name:'MANAURE', code: '560', departaments_id: 19},
  {name:'FONSECA', code: '279', departaments_id: 19},
  {name:'URUMITA', code: '855', departaments_id: 19},
  {name:'RIOHACHA', code: '001', departaments_id: 19},
  {name:'LA JAGUA DEL PILAR', code: '420', departaments_id: 19},
  {name:'PLATO', code: '555', departaments_id: 20},
  {name:'ARIGUANI', code: '058', departaments_id: 20},
  {name:'CHIVOLO', code: '170', departaments_id: 20},
  {name:'SANTA ANA', code: '707', departaments_id: 20},
  {name:'ALGARROBO', code: '030', departaments_id: 20},
  {name:'EL PINON', code: '258', departaments_id: 20},
  {name:'SALAMINA', code: '675', departaments_id: 20},
  {name:'SAN SEBASTIAN DE BUENAVISTA', code: '692', departaments_id: 20},
  {name:'EL RETEN', code: '268', departaments_id: 20},
  {name:'PIVIJAY', code: '551', departaments_id: 20},
  {name:'ARACATACA', code: '053', departaments_id: 20},
  {name:'CONCORDIA', code: '205', departaments_id: 20},
  {name:'EL BANCO', code: '245', departaments_id: 20},
  {name:'PEDRAZA', code: '541', departaments_id: 20},
  {name:'REMOLINO', code: '605', departaments_id: 20},
  {name:'CIENAGA', code: '189', departaments_id: 20},
  {name:'GUAMAL', code: '318', departaments_id: 20},
  {name:'NUEVA GRANADA', code: '460', departaments_id: 20},
  {name:'SANTA MARTA', code: '001', departaments_id: 20},
  {name:'ZAPAYAN', code: '960', departaments_id: 20},
  {name:'CERRO SAN ANTONIO', code: '161', departaments_id: 20},
  {name:'SANTA BARBARA DE PINTO', code: '720', departaments_id: 20},
  {name:'PUEBLOVIEJO', code: '570', departaments_id: 20},
  {name:'TENERIFE', code: '798', departaments_id: 20},
  {name:'SABANAS DE SAN ANGEL', code: '660', departaments_id: 20},
  {name:'PIJINO DEL CARMEN', code: '545', departaments_id: 20},
  {name:'SAN ZENON', code: '703', departaments_id: 20},
  {name:'FUNDACION', code: '288', departaments_id: 20},
  {name:'ZONA BANANERA', code: '980', departaments_id: 20},
  {name:'SITIONUEVO', code: '745', departaments_id: 20},
  {name:'GRANADA', code: '313', departaments_id: 21},
  {name:'PUERTO LOPEZ', code: '573', departaments_id: 21},
  {name:'MAPIRIPAN', code: '325', departaments_id: 21},
  {name:'CABUYARO', code: '124', departaments_id: 21},
  {name:'SAN JUANITO', code: '686', departaments_id: 21},
  {name:'PUERTO LLERAS', code: '577', departaments_id: 21},
  {name:'RESTREPO', code: '606', departaments_id: 21},
  {name:'SAN JUAN DE ARAMA', code: '683', departaments_id: 21},
  {name:'EL CASTILLO', code: '251', departaments_id: 21},
  {name:'PUERTO GAITAN', code: '568', departaments_id: 21},
  {name:'EL DORADO', code: '270', departaments_id: 21},
  {name:'VISTAHERMOSA', code: '711', departaments_id: 21},
  {name:'FUENTE DE ORO', code: '287', departaments_id: 21},
  {name:'PUERTO RICO', code: '590', departaments_id: 21},
  {name:'URIBE', code: '370', departaments_id: 21},
  {name:'SAN CARLOS DE GUAROA', code: '680', departaments_id: 21},
  {name:'GUAMAL', code: '318', departaments_id: 21},
  {name:'CASTILLA LA NUEVA', code: '150', departaments_id: 21},
  {name:'EL CALVARIO', code: '245', departaments_id: 21},
  {name:'MESETAS', code: '330', departaments_id: 21},
  {name:'ACACIAS', code: '006', departaments_id: 21},
  {name:'CUBARRAL', code: '223', departaments_id: 21},
  {name:'VILLAVICENCIO', code: '001', departaments_id: 21},
  {name:'CUMARAL', code: '226', departaments_id: 21},
  {name:'PUERTO CONCORDIA', code: '450', departaments_id: 21},
  {name:'LA MACARENA', code: '350', departaments_id: 21},
  {name:'LEJANIAS', code: '400', departaments_id: 21},
  {name:'SAN MARTIN', code: '689', departaments_id: 21},
  {name:'BARRANCA DE UPIA', code: '110', departaments_id: 21},
  {name:'PUERRES', code: '573', departaments_id: 22},
  {name:'GUACHUCAL', code: '317', departaments_id: 22},
  {name:'GUALMATAN', code: '323', departaments_id: 22},
  {name:'CUMBAL', code: '227', departaments_id: 22},
  {name:'OSPINA', code: '506', departaments_id: 22},
  {name:'SAN BERNARDO', code: '685', departaments_id: 22},
  {name:'EL TAMBO', code: '260', departaments_id: 22},
  {name:'LA CRUZ', code: '378', departaments_id: 22},
  {name:'MOSQUERA', code: '473', departaments_id: 22},
  {name:'GUAITARILLA', code: '320', departaments_id: 22},
  {name:'SANTACRUZ', code: '699', departaments_id: 22},
  {name:'TAMINANGO', code: '786', departaments_id: 22},
  {name:'MAGUI', code: '427', departaments_id: 22},
  {name:'BUESACO', code: '110', departaments_id: 22},
  {name:'ALBAN', code: '019', departaments_id: 22},
  {name:'SAN PEDRO DE CARTAGO', code: '694', departaments_id: 22},
  {name:'ARBOLEDA', code: '051', departaments_id: 22},
  {name:'POTOSI', code: '560', departaments_id: 22},
  {name:'EL ROSARIO', code: '256', departaments_id: 22},
  {name:'LA TOLA', code: '390', departaments_id: 22},
  {name:'CORDOBA', code: '215', departaments_id: 22},
  {name:'CUMBITARA', code: '233', departaments_id: 22},
  {name:'FUNES', code: '287', departaments_id: 22},
  {name:'PROVIDENCIA', code: '565', departaments_id: 22},
  {name:'COLON', code: '203', departaments_id: 22},
  {name:'ROBERTO PAYAN', code: '621', departaments_id: 22},
  {name:'EL CHARCO', code: '250', departaments_id: 22},
  {name:'CUASPUD', code: '224', departaments_id: 22},
  {name:'SAPUYES', code: '720', departaments_id: 22},
  {name:'LA UNION', code: '399', departaments_id: 22},
  {name:'SANTA BARBARA', code: '696', departaments_id: 22},
  {name:'SAN LORENZO', code: '687', departaments_id: 22},
  {name:'ALDANA', code: '022', departaments_id: 22},
  {name:'BARBACOAS', code: '079', departaments_id: 22},
  {name:'CONTADERO', code: '210', departaments_id: 22},
  {name:'IPIALES', code: '356', departaments_id: 22},
  {name:'PASTO', code: '001', departaments_id: 22},
  {name:'RICAURTE', code: '612', departaments_id: 22},
  {name:'SAMANIEGO', code: '678', departaments_id: 22},
  {name:'EL TABLON DE GOMEZ', code: '258', departaments_id: 22},
  {name:'TUQUERRES', code: '838', departaments_id: 22},
  {name:'NARINO', code: '480', departaments_id: 22},
  {name:'BELEN', code: '083', departaments_id: 22},
  {name:'IMUES', code: '354', departaments_id: 22},
  {name:'ILES', code: '352', departaments_id: 22},
  {name:'POLICARPA', code: '540', departaments_id: 22},
  {name:'OLAYA HERRERA', code: '490', departaments_id: 22},
  {name:'SANDONA', code: '683', departaments_id: 22},
  {name:'FRANCISCO PIZARRO', code: '520', departaments_id: 22},
  {name:'EL PENOL', code: '254', departaments_id: 22},
  {name:'YACUANQUER', code: '885', departaments_id: 22},
  {name:'SAN PABLO', code: '693', departaments_id: 22},
  {name:'ANCUYA', code: '036', departaments_id: 22},
  {name:'LA FLORIDA', code: '381', departaments_id: 22},
  {name:'PUPIALES', code: '585', departaments_id: 22},
  {name:'CHACHAGUI', code: '240', departaments_id: 22},
  {name:'LA LLANADA', code: '385', departaments_id: 22},
  {name:'SAN ANDRES DE TUMACO', code: '835', departaments_id: 22},
  {name:'TANGUA', code: '788', departaments_id: 22},
  {name:'LINARES', code: '411', departaments_id: 22},
  {name:'LOS ANDES', code: '418', departaments_id: 22},
  {name:'CONSACA', code: '207', departaments_id: 22},
  {name:'LEIVA', code: '405', departaments_id: 22},
  {name:'MALLAMA', code: '435', departaments_id: 22},
  {name:'EL ZULIA', code: '261', departaments_id: 23},
  {name:'SANTIAGO', code: '680', departaments_id: 23},
  {name:'PUERTO SANTANDER', code: '553', departaments_id: 23},
  {name:'HACARI', code: '344', departaments_id: 23},
  {name:'TIBU', code: '810', departaments_id: 23},
  {name:'SILOS', code: '743', departaments_id: 23},
  {name:'CHITAGA', code: '174', departaments_id: 23},
  {name:'OCANA', code: '498', departaments_id: 23},
  {name:'HERRAN', code: '347', departaments_id: 23},
  {name:'BOCHALEMA', code: '099', departaments_id: 23},
  {name:'CONVENCION', code: '206', departaments_id: 23},
  {name:'CACOTA', code: '125', departaments_id: 23},
  {name:'ABREGO', code: '003', departaments_id: 23},
  {name:'LA PLAYA', code: '398', departaments_id: 23},
  {name:'BUCARASICA', code: '109', departaments_id: 23},
  {name:'SALAZAR', code: '660', departaments_id: 23},
  {name:'EL TARRA', code: '250', departaments_id: 23},
  {name:'LOS PATIOS', code: '405', departaments_id: 23},
  {name:'VILLA CARO', code: '871', departaments_id: 23},
  {name:'LOURDES', code: '418', departaments_id: 23},
  {name:'PAMPLONITA', code: '520', departaments_id: 23},
  {name:'ARBOLEDAS', code: '051', departaments_id: 23},
  {name:'LABATECA', code: '377', departaments_id: 23},
  {name:'VILLA DEL ROSARIO', code: '874', departaments_id: 23},
  {name:'RAGONVALIA', code: '599', departaments_id: 23},
  {name:'CUCUTILLA', code: '223', departaments_id: 23},
  {name:'EL CARMEN', code: '245', departaments_id: 23},
  {name:'PAMPLONA', code: '518', departaments_id: 23},
  {name:'CUCUTA', code: '001', departaments_id: 23},
  {name:'DURANIA', code: '239', departaments_id: 23},
  {name:'CHINACOTA', code: '172', departaments_id: 23},
  {name:'SARDINATA', code: '720', departaments_id: 23},
  {name:'TEORAMA', code: '800', departaments_id: 23},
  {name:'MUTISCUA', code: '480', departaments_id: 23},
  {name:'SAN CAYETANO', code: '673', departaments_id: 23},
  {name:'GRAMALOTE', code: '313', departaments_id: 23},
  {name:'SAN CALIXTO', code: '670', departaments_id: 23},
  {name:'CACHIRA', code: '128', departaments_id: 23},
  {name:'TOLEDO', code: '820', departaments_id: 23},
  {name:'LA ESPERANZA', code: '385', departaments_id: 23},
  {name:'SANTIAGO', code: '760', departaments_id: 24},
  {name:'SIBUNDOY', code: '749', departaments_id: 24},
  {name:'VALLE DEL GUAMUEZ', code: '865', departaments_id: 24},
  {name:'ORITO', code: '320', departaments_id: 24},
  {name:'VILLAGARZON', code: '885', departaments_id: 24},
  {name:'SAN FRANCISCO', code: '755', departaments_id: 24},
  {name:'PUERTO LEGUIZAMO', code: '573', departaments_id: 24},
  {name:'SAN MIGUEL', code: '757', departaments_id: 24},
  {name:'PUERTO GUZMAN', code: '571', departaments_id: 24},
  {name:'PUERTO CAICEDO', code: '569', departaments_id: 24},
  {name:'COLON', code: '219', departaments_id: 24},
  {name:'PUERTO ASIS', code: '568', departaments_id: 24},
  {name:'MOCOA', code: '001', departaments_id: 24},
  {name:'CALARCA', code: '130', departaments_id: 25},
  {name:'BUENAVISTA', code: '111', departaments_id: 25},
  {name:'MONTENEGRO', code: '470', departaments_id: 25},
  {name:'LA TEBAIDA', code: '401', departaments_id: 25},
  {name:'QUIMBAYA', code: '594', departaments_id: 25},
  {name:'GENOVA', code: '302', departaments_id: 25},
  {name:'CORDOBA', code: '212', departaments_id: 25},
  {name:'SALENTO', code: '690', departaments_id: 25},
  {name:'PIJAO', code: '548', departaments_id: 25},
  {name:'FILANDIA', code: '272', departaments_id: 25},
  {name:'ARMENIA', code: '001', departaments_id: 25},
  {name:'CIRCASIA', code: '190', departaments_id: 25},
  {name:'MARSELLA', code: '440', departaments_id: 26},
  {name:'LA VIRGINIA', code: '400', departaments_id: 26},
  {name:'MISTRATO', code: '456', departaments_id: 26},
  {name:'QUINCHIA', code: '594', departaments_id: 26},
  {name:'APIA', code: '045', departaments_id: 26},
  {name:'DOSQUEBRADAS', code: '170', departaments_id: 26},
  {name:'PEREIRA', code: '001', departaments_id: 26},
  {name:'SANTA ROSA DE CABAL', code: '682', departaments_id: 26},
  {name:'SANTUARIO', code: '687', departaments_id: 26},
  {name:'BELEN DE UMBRIA', code: '088', departaments_id: 26},
  {name:'GUATICA', code: '318', departaments_id: 26},
  {name:'LA CELIA', code: '383', departaments_id: 26},
  {name:'BALBOA', code: '075', departaments_id: 26},
  {name:'PUEBLO RICO', code: '572', departaments_id: 26},
  {name:'SAN ANDRES', code: '001', departaments_id: 27},
  {name:'PROVIDENCIA', code: '564', departaments_id: 27},
  {name:'BETULIA', code: '092', departaments_id: 28},
  {name:'OCAMONTE', code: '498', departaments_id: 28},
  {name:'PALMAR', code: '522', departaments_id: 28},
  {name:'AGUADA', code: '013', departaments_id: 28},
  {name:'GUAVATA', code: '324', departaments_id: 28},
  {name:'BARBOSA', code: '077', departaments_id: 28},
  {name:'SAN JOAQUIN', code: '682', departaments_id: 28},
  {name:'SAN ANDRES', code: '669', departaments_id: 28},
  {name:'SANTA HELENA DEL OPON', code: '720', departaments_id: 28},
  {name:'CONCEPCION', code: '207', departaments_id: 28},
  {name:'SANTA BARBARA', code: '705', departaments_id: 28},
  {name:'CURITI', code: '229', departaments_id: 28},
  {name:'ENCISO', code: '266', departaments_id: 28},
  {name:'BARRANCABERMEJA', code: '081', departaments_id: 28},
  {name:'CIMITARRA', code: '190', departaments_id: 28},
  {name:'MOGOTES', code: '464', departaments_id: 28},
  {name:'BOLIVAR', code: '101', departaments_id: 28},
  {name:'PIEDECUESTA', code: '547', departaments_id: 28},
  {name:'CHIMA', code: '176', departaments_id: 28},
  {name:'JESUS MARIA', code: '368', departaments_id: 28},
  {name:'GALAN', code: '296', departaments_id: 28},
  {name:'LA PAZ', code: '397', departaments_id: 28},
  {name:'OIBA', code: '500', departaments_id: 28},
  {name:'RIONEGRO', code: '615', departaments_id: 28},
  {name:'SUAITA', code: '770', departaments_id: 28},
  {name:'HATO', code: '344', departaments_id: 28},
  {name:'SAN BENITO', code: '673', departaments_id: 28},
  {name:'FLORIDABLANCA', code: '276', departaments_id: 28},
  {name:'LA BELLEZA', code: '377', departaments_id: 28},
  {name:'MACARAVITA', code: '425', departaments_id: 28},
  {name:'GUEPSA', code: '327', departaments_id: 28},
  {name:'PUERTO WILCHES', code: '575', departaments_id: 28},
  {name:'TONA', code: '820', departaments_id: 28},
  {name:'GUACA', code: '318', departaments_id: 28},
  {name:'ARATOCA', code: '051', departaments_id: 28},
  {name:'CONFINES', code: '209', departaments_id: 28},
  {name:'LANDAZURI', code: '385', departaments_id: 28},
  {name:'CABRERA', code: '121', departaments_id: 28},
  {name:'PUENTE NACIONAL', code: '572', departaments_id: 28},
  {name:'SAN JOSE DE MIRANDA', code: '684', departaments_id: 28},
  {name:'BUCARAMANGA', code: '001', departaments_id: 28},
  {name:'PINCHOTE', code: '549', departaments_id: 28},
  {name:'CHIPATA', code: '179', departaments_id: 28},
  {name:'ZAPATOCA', code: '895', departaments_id: 28},
  {name:'LOS SANTOS', code: '418', departaments_id: 28},
  {name:'VETAS', code: '867', departaments_id: 28},
  {name:'SUCRE', code: '773', departaments_id: 28},
  {name:'COROMORO', code: '217', departaments_id: 28},
  {name:'ALBANIA', code: '020', departaments_id: 28},
  {name:'ONZAGA', code: '502', departaments_id: 28},
  {name:'EL PLAYON', code: '255', departaments_id: 28},
  {name:'ENCINO', code: '264', departaments_id: 28},
  {name:'PALMAS DEL SOCORRO', code: '524', departaments_id: 28},
  {name:'CAPITANEJO', code: '147', departaments_id: 28},
  {name:'PUERTO PARRA', code: '573', departaments_id: 28},
  {name:'CEPITA', code: '160', departaments_id: 28},
  {name:'LEBRIJA', code: '406', departaments_id: 28},
  {name:'VILLANUEVA', code: '872', departaments_id: 28},
  {name:'SIMACOTA', code: '745', departaments_id: 28},
  {name:'MATANZA', code: '444', departaments_id: 28},
  {name:'SAN MIGUEL', code: '686', departaments_id: 28},
  {name:'CONTRATACION', code: '211', departaments_id: 28},
  {name:'PARAMO', code: '533', departaments_id: 28},
  {name:'EL GUACAMAYO', code: '245', departaments_id: 28},
  {name:'CHARTA', code: '169', departaments_id: 28},
  {name:'SABANA DE TORRES', code: '655', departaments_id: 28},
  {name:'SAN GIL', code: '679', departaments_id: 28},
  {name:'CALIFORNIA', code: '132', departaments_id: 28},
  {name:'CERRITO', code: '162', departaments_id: 28},
  {name:'MOLAGAVITA', code: '468', departaments_id: 28},
  {name:'GUAPOTA', code: '322', departaments_id: 28},
  {name:'GAMBITA', code: '298', departaments_id: 28},
  {name:'EL CARMEN DE CHUCURI', code: '235', departaments_id: 28},
  {name:'CARCASI', code: '152', departaments_id: 28},
  {name:'FLORIAN', code: '271', departaments_id: 28},
  {name:'SAN VICENTE DE CHUCURI', code: '689', departaments_id: 28},
  {name:'SURATA', code: '780', departaments_id: 28},
  {name:'JORDAN', code: '370', departaments_id: 28},
  {name:'GIRON', code: '307', departaments_id: 28},
  {name:'EL PENON', code: '250', departaments_id: 28},
  {name:'MALAGA', code: '432', departaments_id: 28},
  {name:'GUADALUPE', code: '320', departaments_id: 28},
  {name:'BARICHARA', code: '079', departaments_id: 28},
  {name:'VELEZ', code: '861', departaments_id: 28},
  {name:'CHARALA', code: '167', departaments_id: 28},
  {name:'SOCORRO', code: '755', departaments_id: 28},
  {name:'VALLE DE SAN JOSE', code: '855', departaments_id: 28},
  {name:'BUENAVISTA', code: '110', departaments_id: 29},
  {name:'GALERAS', code: '235', departaments_id: 29},
  {name:'SINCELEJO', code: '001', departaments_id: 29},
  {name:'LOS PALMITOS', code: '418', departaments_id: 29},
  {name:'CHALAN', code: '230', departaments_id: 29},
  {name:'CAIMITO', code: '124', departaments_id: 29},
  {name:'OVEJAS', code: '508', departaments_id: 29},
  {name:'TOLU VIEJO', code: '823', departaments_id: 29},
  {name:'MORROA', code: '473', departaments_id: 29},
  {name:'GUARANDA', code: '265', departaments_id: 29},
  {name:'COVENAS', code: '221', departaments_id: 29},
  {name:'PALMITO', code: '523', departaments_id: 29},
  {name:'SAN JUAN DE BETULIA', code: '702', departaments_id: 29},
  {name:'SANTIAGO DE TOLU', code: '820', departaments_id: 29},
  {name:'LA UNION', code: '400', departaments_id: 29},
  {name:'COLOSO', code: '204', departaments_id: 29},
  {name:'EL ROBLE', code: '233', departaments_id: 29},
  {name:'SAN PEDRO', code: '717', departaments_id: 29},
  {name:'SAN MARCOS', code: '708', departaments_id: 29},
  {name:'SAN LUIS DE SINCE', code: '742', departaments_id: 29},
  {name:'MAJAGUAL', code: '429', departaments_id: 29},
  {name:'SAMPUES', code: '670', departaments_id: 29},
  {name:'COROZAL', code: '215', departaments_id: 29},
  {name:'SAN BENITO ABAD', code: '678', departaments_id: 29},
  {name:'SAN ONOFRE', code: '713', departaments_id: 29},
  {name:'SUCRE', code: '771', departaments_id: 29},
  {name:'ARMERO', code: '055', departaments_id: 30},
  {name:'DOLORES', code: '236', departaments_id: 30},
  {name:'LERIDA', code: '408', departaments_id: 30},
  {name:'CHAPARRAL', code: '168', departaments_id: 30},
  {name:'HONDA', code: '349', departaments_id: 30},
  {name:'VILLARRICA', code: '873', departaments_id: 30},
  {name:'CARMEN DE APICALA', code: '148', departaments_id: 30},
  {name:'SAN SEBASTIAN DE MARIQUITA', code: '443', departaments_id: 30},
  {name:'VALLE DE SAN JUAN', code: '854', departaments_id: 30},
  {name:'FRESNO', code: '283', departaments_id: 30},
  {name:'GUAMO', code: '319', departaments_id: 30},
  {name:'SANTA ISABEL', code: '686', departaments_id: 30},
  {name:'SALDANA', code: '671', departaments_id: 30},
  {name:'NATAGAIMA', code: '483', departaments_id: 30},
  {name:'CAJAMARCA', code: '124', departaments_id: 30},
  {name:'ALVARADO', code: '026', departaments_id: 30},
  {name:'SAN ANTONIO', code: '675', departaments_id: 30},
  {name:'ROVIRA', code: '624', departaments_id: 30},
  {name:'COELLO', code: '200', departaments_id: 30},
  {name:'FALAN', code: '270', departaments_id: 30},
  {name:'IBAGUE', code: '001', departaments_id: 30},
  {name:'RIOBLANCO', code: '616', departaments_id: 30},
  {name:'ANZOATEGUI', code: '043', departaments_id: 30},
  {name:'COYAIMA', code: '217', departaments_id: 30},
  {name:'SUAREZ', code: '770', departaments_id: 30},
  {name:'MURILLO', code: '461', departaments_id: 30},
  {name:'PIEDRAS', code: '547', departaments_id: 30},
  {name:'SAN LUIS', code: '678', departaments_id: 30},
  {name:'VENADILLO', code: '861', departaments_id: 30},
  {name:'FLANDES', code: '275', departaments_id: 30},
  {name:'ICONONZO', code: '352', departaments_id: 30},
  {name:'CUNDAY', code: '226', departaments_id: 30},
  {name:'ALPUJARRA', code: '024', departaments_id: 30},
  {name:'RONCESVALLES', code: '622', departaments_id: 30},
  {name:'ESPINAL', code: '268', departaments_id: 30},
  {name:'PRADO', code: '563', departaments_id: 30},
  {name:'AMBALEMA', code: '030', departaments_id: 30},
  {name:'HERVEO', code: '347', departaments_id: 30},
  {name:'LIBANO', code: '411', departaments_id: 30},
  {name:'ATACO', code: '067', departaments_id: 30},
  {name:'MELGAR', code: '449', departaments_id: 30},
  {name:'ORTEGA', code: '504', departaments_id: 30},
  {name:'PURIFICACION', code: '585', departaments_id: 30},
  {name:'VILLAHERMOSA', code: '870', departaments_id: 30},
  {name:'PALOCABILDO', code: '520', departaments_id: 30},
  {name:'CASABIANCA', code: '152', departaments_id: 30},
  {name:'PLANADAS', code: '555', departaments_id: 30},
  {name:'ALCALA', code: '020', departaments_id: 31},
  {name:'LA CUMBRE', code: '377', departaments_id: 31},
  {name:'EL CAIRO', code: '246', departaments_id: 31},
  {name:'RIOFRIO', code: '616', departaments_id: 31},
  {name:'ROLDANILLO', code: '622', departaments_id: 31},
  {name:'EL AGUILA', code: '243', departaments_id: 31},
  {name:'BUGALAGRANDE', code: '113', departaments_id: 31},
  {name:'OBANDO', code: '497', departaments_id: 31},
  {name:'ANDALUCIA', code: '036', departaments_id: 31},
  {name:'BUENAVENTURA', code: '109', departaments_id: 31},
  {name:'GUADALAJARA DE BUGA', code: '111', departaments_id: 31},
  {name:'BOLIVAR', code: '100', departaments_id: 31},
  {name:'ARGELIA', code: '054', departaments_id: 31},
  {name:'CALI', code: '001', departaments_id: 31},
  {name:'TULUA', code: '834', departaments_id: 31},
  {name:'SAN PEDRO', code: '670', departaments_id: 31},
  {name:'ZARZAL', code: '895', departaments_id: 31},
  {name:'VIJES', code: '869', departaments_id: 31},
  {name:'DAGUA', code: '233', departaments_id: 31},
  {name:'CANDELARIA', code: '130', departaments_id: 31},
  {name:'RESTREPO', code: '606', departaments_id: 31},
  {name:'YUMBO', code: '892', departaments_id: 31},
  {name:'TRUJILLO', code: '828', departaments_id: 31},
  {name:'CARTAGO', code: '147', departaments_id: 31},
  {name:'LA VICTORIA', code: '403', departaments_id: 31},
  {name:'YOTOCO', code: '890', departaments_id: 31},
  {name:'EL DOVIO', code: '250', departaments_id: 31},
  {name:'TORO', code: '823', departaments_id: 31},
  {name:'SEVILLA', code: '736', departaments_id: 31},
  {name:'PALMIRA', code: '520', departaments_id: 31},
  {name:'VERSALLES', code: '863', departaments_id: 31},
  {name:'CALIMA', code: '126', departaments_id: 31},
  {name:'FLORIDA', code: '275', departaments_id: 31},
  {name:'CAICEDONIA', code: '122', departaments_id: 31},
  {name:'PRADERA', code: '563', departaments_id: 31},
  {name:'GINEBRA', code: '306', departaments_id: 31},
  {name:'ANSERMANUEVO', code: '041', departaments_id: 31},
  {name:'ULLOA', code: '845', departaments_id: 31},
  {name:'JAMUNDI', code: '364', departaments_id: 31},
  {name:'LA UNION', code: '400', departaments_id: 31},
  {name:'GUACARI', code: '318', departaments_id: 31},
  {name:'EL CERRITO', code: '248', departaments_id: 31},
  {name:'PAPUNAUA', code: '777', departaments_id: 32},
  {name:'CARURU', code: '161', departaments_id: 32},
  {name:'MITU', code: '001', departaments_id: 32},
  {name:'YAVARATE', code: '889', departaments_id: 32},
  {name:'TARAIRA', code: '666', departaments_id: 32},
  {name:'PACOA', code: '511', departaments_id: 32},
  {name:'CUMARIBO', code: '773', departaments_id: 33},
  {name:'PUERTO CARRENO', code: '001', departaments_id: 33},
  {name:'LA PRIMAVERA', code: '524', departaments_id: 33},
  {name:'SANTA ROSALIA', code: '624', departaments_id: 33}
])

IdentificationType.create([
    {name: 'CÉDULA DE CIUDADANÍA', code: '01'},
    {name: 'CÉDULA DE EXTRANJERÍA', code: '02'},
    {name: 'PASAPORTE', code: '03'}
])

Area.create([
    {name: 'PRESIDENCIA', code: '001'},
    {name: 'VICEPRESIDENCIA', code: '002', areas_id: 1},
    {name: 'ÁREA CONTABLE', code: '011', areas_id: 2}
])

Charges.create([
    {name: 'SECRETARIO', code: '001'},
    {name: 'CONTADOR', code: '002'}
])

ContractType.create([
    {name: 'CONTRATO TÉRMINO INDEFINIDO', code: '001'},
    {name: 'CONTRATO TÉRMINO FIJO', code: '002'},
    {name: 'CONTRATO TEMPORAL', code: '003'}
])

Period.create([
    {name: 'AÑO 2018', code: '001', state: 'VIGENTE', date_beg: '01/01/2018', date_end: '01/12/2018'}
])

GoalType.create([
    {name: 'EMPRESARIAL', code: '001'}
])

Genre.create([
    {name: 'FEMENINO', code: '01'},
    {name: 'MASCULINO', code: '02'},
    {name: 'OTRO', code: '03'}
])

GenerationRange.create([
    {name: 'MILENNIAL', code: '01'},
    {name: 'GENERACIÓN X', code: '02'},
    {name: 'BABBY BOOMER', code: '03'}
])

Role.create([
    {name: 'ADMINISTRADOR', code: '01'},
    {name: 'USUARIO', code: '02'}
])

User.create([

])
