# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Departament.create([
  {name:'AMAZONAS', code: '91'},
  {name:'ANTIOQUIA', code: '05'},
  {name:'ARAUCA', code: '81'},
  {name:'ATLANTICO', code: '08'},
  {name:'BOGOTA', code: '11'},
  {name:'BOLIVAR', code: '13'},
  {name:'BOYACA', code: '15'},
  {name:'CALDAS', code: '17'},
  {name:'CAQUETA', code: '18'},
  {name:'CASANARE', code: '85'},
  {name:'CAUCA', code: '19'},
  {name:'CESAR', code: '20'},
  {name:'CHOCO', code: '27'},
  {name:'CORDOBA', code: '23'},
  {name:'CUNDINAMARCA', code: '25'},
  {name:'GUAINIA', code: '94'},
  {name:'GUAVIARE', code: '95'},
  {name:'HUILA', code: '41'},
  {name:'LA GUAJIRA', code: '44'},
  {name:'MAGDALENA', code: '47'},
  {name:'META', code: '50'},
  {name:'NARINO', code: '52'},
  {name:'NORTE DE SANTANDER', code: '54'},
  {name:'PUTUMAYO', code: '86'},
  {name:'QUINDIO', code: '63'},
  {name:'RISARALDA', code: '66'},
  {name:'SAN ANDRES', code: '88'},
  {name:'SANTANDER', code: '68'},
  {name:'SUCRE', code: '70'},
  {name:'TOLIMA', code: '73'},
  {name:'VALLE', code: '76'},
  {name:'VAUPES', code: '97'},
  {name:'VICHADA', code: '99'}
])

City.create([
  {name:'PUERTO SANTANDER', code: '669', departament_id: 1},
  {name:'PUERTO ALEGRIA', code: '530', departament_id: 1},
  {name:'EL ENCANTO', code: '263', departament_id: 1},
  {name:'LA CHORRERA', code: '405', departament_id: 1},
  {name:'TARAPACA', code: '798', departament_id: 1},
  {name:'PUERTO NARINO', code: '540', departament_id: 1},
  {name:'LETICIA', code: '001', departament_id: 1},
  {name:'LA VICTORIA', code: '430', departament_id: 1},
  {name:'MIRITI - PARANA', code: '460', departament_id: 1},
  {name:'LA PEDRERA', code: '407', departament_id: 1},
  {name:'PUERTO ARICA', code: '536', departament_id: 1},
  {name:'SAN CARLOS', code: '649', departament_id: 2},
  {name:'BETULIA', code: '093', departament_id: 2},
  {name:'ANGOSTURA', code: '038', departament_id: 2},
  {name:'SAN JOSE DE LA MONTANA', code: '658', departament_id: 2},
  {name:'VALPARAISO', code: '856', departament_id: 2},
  {name:'BELLO', code: '088', departament_id: 2},
  {name:'GUATAPE', code: '321', departament_id: 2},
  {name:'CANASGORDAS', code: '138', departament_id: 2},
  {name:'CARACOLI', code: '142', departament_id: 2},
  {name:'BARBOSA', code: '079', departament_id: 2},
  {name:'SAN VICENTE', code: '674', departament_id: 2},
  {name:'EBEJICO', code: '240', departament_id: 2},
  {name:'SAN ANDRES DE CUERQUIA', code: '647', departament_id: 2},
  {name:'TAMESIS', code: '789', departament_id: 2},
  {name:'COCORNA', code: '197', departament_id: 2},
  {name:'CONCORDIA', code: '209', departament_id: 2},
  {name:'GIRARDOTA', code: '308', departament_id: 2},
  {name:'CONCEPCION', code: '206', departament_id: 2},
  {name:'SAN ROQUE', code: '670', departament_id: 2},
  {name:'LA UNION', code: '400', departament_id: 2},
  {name:'SANTA BARBARA', code: '679', departament_id: 2},
  {name:'SABANALARGA', code: '628', departament_id: 2},
  {name:'MUTATA', code: '480', departament_id: 2},
  {name:'LA CEJA', code: '376', departament_id: 2},
  {name:'SAN JUAN DE URABA', code: '659', departament_id: 2},
  {name:'HISPANIA', code: '353', departament_id: 2},
  {name:'SALGAR', code: '642', departament_id: 2},
  {name:'SONSON', code: '756', departament_id: 2},
  {name:'GIRALDO', code: '306', departament_id: 2},
  {name:'ANGELOPOLIS', code: '036', departament_id: 2},
  {name:'CIUDAD BOLIVAR', code: '101', departament_id: 2},
  {name:'VIGIA DEL FUERTE', code: '873', departament_id: 2},
  {name:'CISNEROS', code: '190', departament_id: 2},
  {name:'SANTA ROSA DE OSOS', code: '686', departament_id: 2},
  {name:'AMALFI', code: '031', departament_id: 2},
  {name:'ANZA', code: '044', departament_id: 2},
  {name:'TARSO', code: '792', departament_id: 2},
  {name:'ARMENIA', code: '059', departament_id: 2},
  {name:'TOLEDO', code: '819', departament_id: 2},
  {name:'CAICEDO', code: '125', departament_id: 2},
  {name:'BRICENO', code: '107', departament_id: 2},
  {name:'JERICO', code: '368', departament_id: 2},
  {name:'ZARAGOZA', code: '895', departament_id: 2},
  {name:'HELICONIA', code: '347', departament_id: 2},
  {name:'RIONEGRO', code: '615', departament_id: 2},
  {name:'REMEDIOS', code: '604', departament_id: 2},
  {name:'NECOCLI', code: '490', departament_id: 2},
  {name:'TURBO', code: '837', departament_id: 2},
  {name:'PUERTO TRIUNFO', code: '591', departament_id: 2},
  {name:'URRAO', code: '847', departament_id: 2},
  {name:'SAN LUIS', code: '660', departament_id: 2},
  {name:'OLAYA', code: '501', departament_id: 2},
  {name:'SAN JERONIMO', code: '656', departament_id: 2},
  {name:'URAMITA', code: '842', departament_id: 2},
  {name:'SABANETA', code: '631', departament_id: 2},
  {name:'ANDES', code: '034', departament_id: 2},
  {name:'NARINO', code: '483', departament_id: 2},
  {name:'JARDIN', code: '364', departament_id: 2},
  {name:'EL SANTUARIO', code: '697', departament_id: 2},
  {name:'SAN PEDRO DE LOS MILAGROS', code: '664', departament_id: 2},
  {name:'PUERTO BERRIO', code: '579', departament_id: 2},
  {name:'CACERES', code: '120', departament_id: 2},
  {name:'BELMIRA', code: '086', departament_id: 2},
  {name:'PEQUE', code: '543', departament_id: 2},
  {name:'COPACABANA', code: '212', departament_id: 2},
  {name:'ABRIAQUI', code: '004', departament_id: 2},
  {name:'BETANIA', code: '091', departament_id: 2},
  {name:'LIBORINA', code: '411', departament_id: 2},
  {name:'MEDELLIN', code: '001', departament_id: 2},
  {name:'PUERTO NARE', code: '585', departament_id: 2},
  {name:'YOLOMBO', code: '890', departament_id: 2},
  {name:'CAMPAMENTO', code: '134', departament_id: 2},
  {name:'DABEIBA', code: '234', departament_id: 2},
  {name:'GUARNE', code: '318', departament_id: 2},
  {name:'SOPETRAN', code: '761', departament_id: 2},
  {name:'ITUANGO', code: '361', departament_id: 2},
  {name:'RETIRO', code: '607', departament_id: 2},
  {name:'FREDONIA', code: '282', departament_id: 2},
  {name:'MACEO', code: '425', departament_id: 2},
  {name:'YONDO', code: '893', departament_id: 2},
  {name:'ARBOLETES', code: '051', departament_id: 2},
  {name:'SAN RAFAEL', code: '667', departament_id: 2},
  {name:'GUADALUPE', code: '315', departament_id: 2},
  {name:'AMAGA', code: '030', departament_id: 2},
  {name:'ENTRERRIOS', code: '264', departament_id: 2},
  {name:'SEGOVIA', code: '736', departament_id: 2},
  {name:'GOMEZ PLATA', code: '310', departament_id: 2},
  {name:'YALI', code: '885', departament_id: 2},
  {name:'SAN PEDRO DE URABA', code: '665', departament_id: 2},
  {name:'NECHI', code: '495', departament_id: 2},
  {name:'CALDAS', code: '129', departament_id: 2},
  {name:'ANORI', code: '040', departament_id: 2},
  {name:'TITIRIBI', code: '809', departament_id: 2},
  {name:'TARAZA', code: '790', departament_id: 2},
  {name:'ABEJORRAL', code: '002', departament_id: 2},
  {name:'MARINILLA', code: '440', departament_id: 2},
  {name:'EL CARMEN DE VIBORAL', code: '148', departament_id: 2},
  {name:'LA ESTRELLA', code: '380', departament_id: 2},
  {name:'VALDIVIA', code: '854', departament_id: 2},
  {name:'CARAMANTA', code: '145', departament_id: 2},
  {name:'PENOL', code: '541', departament_id: 2},
  {name:'CAREPA', code: '147', departament_id: 2},
  {name:'GRANADA', code: '313', departament_id: 2},
  {name:'VENECIA', code: '861', departament_id: 2},
  {name:'FRONTINO', code: '284', departament_id: 2},
  {name:'APARTADO', code: '045', departament_id: 2},
  {name:'DONMATIAS', code: '237', departament_id: 2},
  {name:'ITAGUI', code: '360', departament_id: 2},
  {name:'SANTAFE DE ANTIOQUIA', code: '042', departament_id: 2},
  {name:'MONTEBELLO', code: '467', departament_id: 2},
  {name:'CHIGORODO', code: '172', departament_id: 2},
  {name:'BURITICA', code: '113', departament_id: 2},
  {name:'ARGELIA', code: '055', departament_id: 2},
  {name:'CAUCASIA', code: '154', departament_id: 2},
  {name:'SAN FRANCISCO', code: '652', departament_id: 2},
  {name:'YARUMAL', code: '887', departament_id: 2},
  {name:'MURINDO', code: '475', departament_id: 2},
  {name:'VEGACHI', code: '858', departament_id: 2},
  {name:'PUEBLORRICO', code: '576', departament_id: 2},
  {name:'LA PINTADA', code: '390', departament_id: 2},
  {name:'EL BAGRE', code: '250', departament_id: 2},
  {name:'ENVIGADO', code: '266', departament_id: 2},
  {name:'SANTO DOMINGO', code: '690', departament_id: 2},
  {name:'ALEJANDRIA', code: '021', departament_id: 2},
  {name:'CAROLINA', code: '150', departament_id: 2},
  {name:'ARAUQUITA', code: '065', departament_id: 3},
  {name:'FORTUL', code: '300', departament_id: 3},
  {name:'PUERTO RONDON', code: '591', departament_id: 3},
  {name:'TAME', code: '794', departament_id: 3},
  {name:'ARAUCA', code: '001', departament_id: 3},
  {name:'CRAVO NORTE', code: '220', departament_id: 3},
  {name:'SARAVENA', code: '736', departament_id: 3},
  {name:'USIACURI', code: '849', departament_id: 4},
  {name:'TUBARA', code: '832', departament_id: 4},
  {name:'SUAN', code: '770', departament_id: 4},
  {name:'GALAPA', code: '296', departament_id: 4},
  {name:'BARRANQUILLA', code: '001', departament_id: 4},
  {name:'JUAN DE ACOSTA', code: '372', departament_id: 4},
  {name:'MALAMBO', code: '433', departament_id: 4},
  {name:'MANATI', code: '436', departament_id: 4},
  {name:'SABANAGRANDE', code: '634', departament_id: 4},
  {name:'PIOJO', code: '549', departament_id: 4},
  {name:'CAMPO DE LA CRUZ', code: '137', departament_id: 4},
  {name:'SABANALARGA', code: '638', departament_id: 4},
  {name:'BARANOA', code: '078', departament_id: 4},
  {name:'POLONUEVO', code: '558', departament_id: 4},
  {name:'LURUACO', code: '421', departament_id: 4},
  {name:'REPELON', code: '606', departament_id: 4},
  {name:'CANDELARIA', code: '141', departament_id: 4},
  {name:'SANTO TOMAS', code: '685', departament_id: 4},
  {name:'SANTA LUCIA', code: '675', departament_id: 4},
  {name:'PUERTO COLOMBIA', code: '573', departament_id: 4},
  {name:'SOLEDAD', code: '758', departament_id: 4},
  {name:'PONEDERA', code: '560', departament_id: 4},
  {name:'PALMAR DE VARELA', code: '520', departament_id: 4},
  {name:'BOGOTA DC', code: '001', departament_id: 5},
  {name:'SANTA CATALINA', code: '673', departament_id: 6},
  {name:'ZAMBRANO', code: '894', departament_id: 6},
  {name:'SAN PABLO', code: '670', departament_id: 6},
  {name:'SAN MARTIN DE LOBA', code: '667', departament_id: 6},
  {name:'EL CARMEN DE BOLIVAR', code: '244', departament_id: 6},
  {name:'BARRANCO DE LOBA', code: '074', departament_id: 6},
  {name:'SIMITI', code: '744', departament_id: 6},
  {name:'TIQUISIO', code: '810', departament_id: 6},
  {name:'SAN JUAN NEPOMUCENO', code: '657', departament_id: 6},
  {name:'SANTA ROSA DEL SUR', code: '688', departament_id: 6},
  {name:'NOROSI', code: '490', departament_id: 6},
  {name:'CARTAGENA', code: '001', departament_id: 6},
  {name:'CICUCO', code: '188', departament_id: 6},
  {name:'MONTECRISTO', code: '458', departament_id: 6},
  {name:'VILLANUEVA', code: '873', departament_id: 6},
  {name:'ACHI', code: '006', departament_id: 6},
  {name:'MORALES', code: '473', departament_id: 6},
  {name:'PINILLOS', code: '549', departament_id: 6},
  {name:'HATILLO DE LOBA', code: '300', departament_id: 6},
  {name:'RIO VIEJO', code: '600', departament_id: 6},
  {name:'MOMPOS', code: '468', departament_id: 6},
  {name:'MAHATES', code: '433', departament_id: 6},
  {name:'SANTA ROSA', code: '683', departament_id: 6},
  {name:'TALAIGUA NUEVO', code: '780', departament_id: 6},
  {name:'ARROYOHONDO', code: '062', departament_id: 6},
  {name:'SAN JACINTO DEL CAUCA', code: '655', departament_id: 6},
  {name:'SAN CRISTOBAL', code: '620', departament_id: 6},
  {name:'CALAMAR', code: '140', departament_id: 6},
  {name:'SAN JACINTO', code: '654', departament_id: 6},
  {name:'MARIA LA BAJA', code: '442', departament_id: 6},
  {name:'MAGANGUE', code: '430', departament_id: 6},
  {name:'CORDOBA', code: '212', departament_id: 6},
  {name:'SOPLAVIENTO', code: '760', departament_id: 6},
  {name:'TURBACO', code: '836', departament_id: 6},
  {name:'CANTAGALLO', code: '160', departament_id: 6},
  {name:'ARENAL', code: '042', departament_id: 6},
  {name:'EL GUAMO', code: '248', departament_id: 6},
  {name:'SAN FERNANDO', code: '650', departament_id: 6},
  {name:'ALTOS DEL ROSARIO', code: '030', departament_id: 6},
  {name:'TURBANA', code: '838', departament_id: 6},
  {name:'EL PENON', code: '268', departament_id: 6},
  {name:'ARJONA', code: '052', departament_id: 6},
  {name:'CLEMENCIA', code: '222', departament_id: 6},
  {name:'SAN ESTANISLAO', code: '647', departament_id: 6},
  {name:'REGIDOR', code: '580', departament_id: 6},
  {name:'MARGARITA', code: '440', departament_id: 6},
  {name:'VENTAQUEMADA', code: '861', departament_id: 7},
  {name:'ZETAQUIRA', code: '897', departament_id: 7},
  {name:'TOPAGA', code: '820', departament_id: 7},
  {name:'CORRALES', code: '215', departament_id: 7},
  {name:'TENZA', code: '798', departament_id: 7},
  {name:'TURMEQUE', code: '835', departament_id: 7},
  {name:'MONGUA', code: '464', departament_id: 7},
  {name:'FIRAVITOBA', code: '272', departament_id: 7},
  {name:'GUAYATA', code: '325', departament_id: 7},
  {name:'MACANAL', code: '425', departament_id: 7},
  {name:'EL COCUY', code: '244', departament_id: 7},
  {name:'SANTA SOFIA', code: '696', departament_id: 7},
  {name:'VILLA DE LEYVA', code: '407', departament_id: 7},
  {name:'CUITIVA', code: '226', departament_id: 7},
  {name:'TUTA', code: '837', departament_id: 7},
  {name:'SOGAMOSO', code: '759', departament_id: 7},
  {name:'BELEN', code: '087', departament_id: 7},
  {name:'OICATA', code: '500', departament_id: 7},
  {name:'CHIVATA', code: '187', departament_id: 7},
  {name:'COPER', code: '212', departament_id: 7},
  {name:'LA VICTORIA', code: '401', departament_id: 7},
  {name:'MUZO', code: '480', departament_id: 7},
  {name:'TIBASOSA', code: '806', departament_id: 7},
  {name:'JENESANO', code: '367', departament_id: 7},
  {name:'BRICENO', code: '106', departament_id: 7},
  {name:'JERICO', code: '368', departament_id: 7},
  {name:'QUIPAMA', code: '580', departament_id: 7},
  {name:'LABRANZAGRANDE', code: '377', departament_id: 7},
  {name:'SORACA', code: '764', departament_id: 7},
  {name:'CHISCAS', code: '180', departament_id: 7},
  {name:'TUNUNGUA', code: '832', departament_id: 7},
  {name:'PANQUEBA', code: '522', departament_id: 7},
  {name:'TIBANA', code: '804', departament_id: 7},
  {name:'PAJARITO', code: '518', departament_id: 7},
  {name:'PUERTO BOYACA', code: '572', departament_id: 7},
  {name:'SOTAQUIRA', code: '763', departament_id: 7},
  {name:'PESCA', code: '542', departament_id: 7},
  {name:'BOYACA', code: '104', departament_id: 7},
  {name:'MONGUI', code: '466', departament_id: 7},
  {name:'CAMPOHERMOSO', code: '135', departament_id: 7},
  {name:'COVARACHIA', code: '218', departament_id: 7},
  {name:'SUTAMARCHAN', code: '776', departament_id: 7},
  {name:'SAN MIGUEL DE SEMA', code: '676', departament_id: 7},
  {name:'AQUITANIA', code: '047', departament_id: 7},
  {name:'PAUNA', code: '531', departament_id: 7},
  {name:'TIPACOQUE', code: '810', departament_id: 7},
  {name:'LA CAPILLA', code: '380', departament_id: 7},
  {name:'SABOYA', code: '632', departament_id: 7},
  {name:'PAYA', code: '533', departament_id: 7},
  {name:'ALMEIDA', code: '022', departament_id: 7},
  {name:'CHITARAQUE', code: '185', departament_id: 7},
  {name:'TUNJA', code: '001', departament_id: 7},
  {name:'TUTAZA', code: '839', departament_id: 7},
  {name:'SAN JOSE DE PARE', code: '664', departament_id: 7},
  {name:'MOTAVITA', code: '476', departament_id: 7},
  {name:'BUENAVISTA', code: '109', departament_id: 7},
  {name:'TASCO', code: '790', departament_id: 7},
  {name:'TOCA', code: '814', departament_id: 7},
  {name:'MARIPI', code: '442', departament_id: 7},
  {name:'OTANCHE', code: '507', departament_id: 7},
  {name:'CUCAITA', code: '224', departament_id: 7},
  {name:'SAMACA', code: '646', departament_id: 7},
  {name:'SATIVANORTE', code: '720', departament_id: 7},
  {name:'PAIPA', code: '516', departament_id: 7},
  {name:'RONDON', code: '621', departament_id: 7},
  {name:'BUSBANZA', code: '114', departament_id: 7},
  {name:'SAN EDUARDO', code: '660', departament_id: 7},
  {name:'BERBEO', code: '090', departament_id: 7},
  {name:'SANTA ROSA DE VITERBO', code: '693', departament_id: 7},
  {name:'SANTANA', code: '686', departament_id: 7},
  {name:'GACHANTIVA', code: '293', departament_id: 7},
  {name:'SOCHA', code: '757', departament_id: 7},
  {name:'PAZ DE RIO', code: '537', departament_id: 7},
  {name:'SIACHOQUE', code: '740', departament_id: 7},
  {name:'BETEITIVA', code: '092', departament_id: 7},
  {name:'SORA', code: '762', departament_id: 7},
  {name:'SACHICA', code: '638', departament_id: 7},
  {name:'CHINAVITA', code: '172', departament_id: 7},
  {name:'CERINZA', code: '162', departament_id: 7},
  {name:'UMBITA', code: '842', departament_id: 7},
  {name:'NUEVO COLON', code: '494', departament_id: 7},
  {name:'CALDAS', code: '131', departament_id: 7},
  {name:'GARAGOA', code: '299', departament_id: 7},
  {name:'PACHAVITA', code: '511', departament_id: 7},
  {name:'SOATA', code: '753', departament_id: 7},
  {name:'SOCOTA', code: '755', departament_id: 7},
  {name:'CIENEGA', code: '189', departament_id: 7},
  {name:'PISBA', code: '550', departament_id: 7},
  {name:'GUACAMAYAS', code: '317', departament_id: 7},
  {name:'EL ESPINO', code: '248', departament_id: 7},
  {name:'MIRAFLORES', code: '455', departament_id: 7},
  {name:'GAMEZA', code: '296', departament_id: 7},
  {name:'SAN PABLO DE BORBUR', code: '681', departament_id: 7},
  {name:'CHIVOR', code: '236', departament_id: 7},
  {name:'GUICAN', code: '332', departament_id: 7},
  {name:'CUBARA', code: '223', departament_id: 7},
  {name:'SAN LUIS DE GACENO', code: '667', departament_id: 7},
  {name:'PAEZ', code: '514', departament_id: 7},
  {name:'SAN MATEO', code: '673', departament_id: 7},
  {name:'TOGUI', code: '816', departament_id: 7},
  {name:'CHIQUIZA', code: '232', departament_id: 7},
  {name:'RAMIRIQUI', code: '599', departament_id: 7},
  {name:'RAQUIRA', code: '600', departament_id: 7},
  {name:'LA UVITA', code: '403', departament_id: 7},
  {name:'SUSACON', code: '774', departament_id: 7},
  {name:'TINJACA', code: '808', departament_id: 7},
  {name:'NOBSA', code: '491', departament_id: 7},
  {name:'GUATEQUE', code: '322', departament_id: 7},
  {name:'IZA', code: '362', departament_id: 7},
  {name:'BOAVITA', code: '097', departament_id: 7},
  {name:'SOMONDOCO', code: '761', departament_id: 7},
  {name:'FLORESTA', code: '276', departament_id: 7},
  {name:'TOTA', code: '822', departament_id: 7},
  {name:'CHITA', code: '183', departament_id: 7},
  {name:'SUTATENZA', code: '778', departament_id: 7},
  {name:'SATIVASUR', code: '723', departament_id: 7},
  {name:'VIRACACHA', code: '879', departament_id: 7},
  {name:'CHIQUINQUIRA', code: '176', departament_id: 7},
  {name:'MONIQUIRA', code: '469', departament_id: 7},
  {name:'SANTA MARIA', code: '690', departament_id: 7},
  {name:'ARCABUCO', code: '051', departament_id: 7},
  {name:'DUITAMA', code: '238', departament_id: 7},
  {name:'COMBITA', code: '204', departament_id: 7},
  {name:'NORCASIA', code: '495', departament_id: 8},
  {name:'MANIZALES', code: '001', departament_id: 8},
  {name:'RIOSUCIO', code: '614', departament_id: 8},
  {name:'MARQUETALIA', code: '444', departament_id: 8},
  {name:'SUPIA', code: '777', departament_id: 8},
  {name:'CHINCHINA', code: '174', departament_id: 8},
  {name:'MANZANARES', code: '433', departament_id: 8},
  {name:'AGUADAS', code: '013', departament_id: 8},
  {name:'PACORA', code: '513', departament_id: 8},
  {name:'LA MERCED', code: '388', departament_id: 8},
  {name:'LA DORADA', code: '380', departament_id: 8},
  {name:'VITERBO', code: '877', departament_id: 8},
  {name:'SAMANA', code: '662', departament_id: 8},
  {name:'VICTORIA', code: '867', departament_id: 8},
  {name:'RISARALDA', code: '616', departament_id: 8},
  {name:'FILADELFIA', code: '272', departament_id: 8},
  {name:'ANSERMA', code: '042', departament_id: 8},
  {name:'BELALCAZAR', code: '088', departament_id: 8},
  {name:'MARMATO', code: '442', departament_id: 8},
  {name:'PENSILVANIA', code: '541', departament_id: 8},
  {name:'PALESTINA', code: '524', departament_id: 8},
  {name:'NEIRA', code: '486', departament_id: 8},
  {name:'ARANZAZU', code: '050', departament_id: 8},
  {name:'VILLAMARIA', code: '873', departament_id: 8},
  {name:'MARULANDA', code: '446', departament_id: 8},
  {name:'SAN JOSE', code: '665', departament_id: 8},
  {name:'SALAMINA', code: '653', departament_id: 8},
  {name:'FLORENCIA', code: '001', departament_id: 9},
  {name:'EL DONCELLO', code: '247', departament_id: 9},
  {name:'SAN VICENTE DEL CAGUAN', code: '753', departament_id: 9},
  {name:'ALBANIA', code: '029', departament_id: 9},
  {name:'SOLANO', code: '756', departament_id: 9},
  {name:'EL PAUJIL', code: '256', departament_id: 9},
  {name:'CARTAGENA DEL CHAIRA', code: '150', departament_id: 9},
  {name:'VALPARAISO', code: '860', departament_id: 9},
  {name:'BELEN DE LOS ANDAQUIES', code: '094', departament_id: 9},
  {name:'SOLITA', code: '785', departament_id: 9},
  {name:'MILAN', code: '460', departament_id: 9},
  {name:'LA MONTANITA', code: '410', departament_id: 9},
  {name:'PUERTO RICO', code: '592', departament_id: 9},
  {name:'CURILLO', code: '205', departament_id: 9},
  {name:'MORELIA', code: '479', departament_id: 9},
  {name:'SAN JOSE DEL FRAGUA', code: '610', departament_id: 9},
  {name:'AGUAZUL', code: '010', departament_id: 10},
  {name:'MONTERREY', code: '162', departament_id: 10},
  {name:'HATO COROZAL', code: '125', departament_id: 10},
  {name:'CHAMEZA', code: '015', departament_id: 10},
  {name:'RECETOR', code: '279', departament_id: 10},
  {name:'PORE', code: '263', departament_id: 10},
  {name:'SABANALARGA', code: '300', departament_id: 10},
  {name:'SAN LUIS DE PALENQUE', code: '325', departament_id: 10},
  {name:'VILLANUEVA', code: '440', departament_id: 10},
  {name:'LA SALINA', code: '136', departament_id: 10},
  {name:'MANI', code: '139', departament_id: 10},
  {name:'YOPAL', code: '001', departament_id: 10},
  {name:'NUNCHIA', code: '225', departament_id: 10},
  {name:'SACAMA', code: '315', departament_id: 10},
  {name:'TAMARA', code: '400', departament_id: 10},
  {name:'TRINIDAD', code: '430', departament_id: 10},
  {name:'PAZ DE ARIPORO', code: '250', departament_id: 10},
  {name:'OROCUE', code: '230', departament_id: 10},
  {name:'TAURAMENA', code: '410', departament_id: 10},
  {name:'FLORENCIA', code: '290', departament_id: 11},
  {name:'TIMBIO', code: '807', departament_id: 11},
  {name:'GUACHENE', code: '300', departament_id: 11},
  {name:'LA SIERRA', code: '392', departament_id: 11},
  {name:'CORINTO', code: '212', departament_id: 11},
  {name:'TOTORO', code: '824', departament_id: 11},
  {name:'BUENOS AIRES', code: '110', departament_id: 11},
  {name:'SANTA ROSA', code: '701', departament_id: 11},
  {name:'POPAYAN', code: '001', departament_id: 11},
  {name:'SANTANDER DE QUILICHAO', code: '698', departament_id: 11},
  {name:'ARGELIA', code: '050', departament_id: 11},
  {name:'JAMBALO', code: '364', departament_id: 11},
  {name:'CAJIBIO', code: '130', departament_id: 11},
  {name:'SUCRE', code: '785', departament_id: 11},
  {name:'MORALES', code: '473', departament_id: 11},
  {name:'LA VEGA', code: '397', departament_id: 11},
  {name:'PADILLA', code: '513', departament_id: 11},
  {name:'LOPEZ', code: '418', departament_id: 11},
  {name:'PAEZ', code: '517', departament_id: 11},
  {name:'PIAMONTE', code: '533', departament_id: 11},
  {name:'SUAREZ', code: '780', departament_id: 11},
  {name:'PURACE', code: '585', departament_id: 11},
  {name:'BOLIVAR', code: '100', departament_id: 11},
  {name:'PUERTO TEJADA', code: '573', departament_id: 11},
  {name:'ALMAGUER', code: '022', departament_id: 11},
  {name:'PIENDAMO', code: '548', departament_id: 11},
  {name:'TIMBIQUI', code: '809', departament_id: 11},
  {name:'INZA', code: '355', departament_id: 11},
  {name:'EL TAMBO', code: '256', departament_id: 11},
  {name:'ROSAS', code: '622', departament_id: 11},
  {name:'CALOTO', code: '142', departament_id: 11},
  {name:'SAN SEBASTIAN', code: '693', departament_id: 11},
  {name:'VILLA RICA', code: '845', departament_id: 11},
  {name:'PATIA', code: '532', departament_id: 11},
  {name:'SILVIA', code: '743', departament_id: 11},
  {name:'GUAPI', code: '318', departament_id: 11},
  {name:'SOTARA', code: '760', departament_id: 11},
  {name:'MIRANDA', code: '455', departament_id: 11},
  {name:'CALDONO', code: '137', departament_id: 11},
  {name:'BALBOA', code: '075', departament_id: 11},
  {name:'TORIBIO', code: '821', departament_id: 11},
  {name:'MERCADERES', code: '450', departament_id: 11},
  {name:'LA GLORIA', code: '383', departament_id: 12},
  {name:'SAN ALBERTO', code: '710', departament_id: 12},
  {name:'AGUSTIN CODAZZI', code: '013', departament_id: 12},
  {name:'CHIRIGUANA', code: '178', departament_id: 12},
  {name:'MANAURE', code: '443', departament_id: 12},
  {name:'TAMALAMEQUE', code: '787', departament_id: 12},
  {name:'SAN DIEGO', code: '750', departament_id: 12},
  {name:'EL COPEY', code: '238', departament_id: 12},
  {name:'EL PASO', code: '250', departament_id: 12},
  {name:'LA JAGUA DE IBIRICO', code: '400', departament_id: 12},
  {name:'RIO DE ORO', code: '614', departament_id: 12},
  {name:'GAMARRA', code: '295', departament_id: 12},
  {name:'CURUMANI', code: '228', departament_id: 12},
  {name:'PUEBLO BELLO', code: '570', departament_id: 12},
  {name:'BECERRIL', code: '045', departament_id: 12},
  {name:'PELAYA', code: '550', departament_id: 12},
  {name:'BOSCONIA', code: '060', departament_id: 12},
  {name:'CHIMICHAGUA', code: '175', departament_id: 12},
  {name:'VALLEDUPAR', code: '001', departament_id: 12},
  {name:'GONZALEZ', code: '310', departament_id: 12},
  {name:'PAILITAS', code: '517', departament_id: 12},
  {name:'AGUACHICA', code: '011', departament_id: 12},
  {name:'SAN MARTIN', code: '770', departament_id: 12},
  {name:'ASTREA', code: '032', departament_id: 12},
  {name:'LA PAZ', code: '621', departament_id: 12},
  {name:'ATRATO', code: '050', departament_id: 13},
  {name:'CERTEGUI', code: '160', departament_id: 13},
  {name:'RIOSUCIO', code: '615', departament_id: 13},
  {name:'NOVITA', code: '491', departament_id: 13},
  {name:'TADO', code: '787', departament_id: 13},
  {name:'EL CARMEN DE ATRATO', code: '245', departament_id: 13},
  {name:'EL CANTON DEL SAN PABLO', code: '135', departament_id: 13},
  {name:'QUIBDO', code: '001', departament_id: 13},
  {name:'CARMEN DEL DARIEN', code: '150', departament_id: 13},
  {name:'MEDIO ATRATO', code: '425', departament_id: 13},
  {name:'BAGADO', code: '073', departament_id: 13},
  {name:'LLORO', code: '413', departament_id: 13},
  {name:'CONDOTO', code: '205', departament_id: 13},
  {name:'RIO QUITO', code: '600', departament_id: 13},
  {name:'SIPI', code: '745', departament_id: 13},
  {name:'ISTMINA', code: '361', departament_id: 13},
  {name:'UNION PANAMERICANA', code: '810', departament_id: 13},
  {name:'BAJO BAUDO', code: '077', departament_id: 13},
  {name:'SAN JOSE DEL PALMAR', code: '660', departament_id: 13},
  {name:'ALTO BAUDO', code: '025', departament_id: 13},
  {name:'MEDIO BAUDO', code: '430', departament_id: 13},
  {name:'ACANDI', code: '006', departament_id: 13},
  {name:'UNGUIA', code: '800', departament_id: 13},
  {name:'MEDIO SAN JUAN', code: '450', departament_id: 13},
  {name:'BOJAYA', code: '099', departament_id: 13},
  {name:'JURADO', code: '372', departament_id: 13},
  {name:'EL LITORAL DEL SAN JUAN', code: '250', departament_id: 13},
  {name:'RIO IRO', code: '580', departament_id: 13},
  {name:'BAHIA SOLANO', code: '075', departament_id: 13},
  {name:'NUQUI', code: '495', departament_id: 13},
  {name:'SAN CARLOS', code: '678', departament_id: 14},
  {name:'SAN BERNARDO DEL VIENTO', code: '675', departament_id: 14},
  {name:'BUENAVISTA', code: '079', departament_id: 14},
  {name:'LOS CORDOBAS', code: '419', departament_id: 14},
  {name:'CIENAGA DE ORO', code: '189', departament_id: 14},
  {name:'PUERTO ESCONDIDO', code: '574', departament_id: 14},
  {name:'PLANETA RICA', code: '555', departament_id: 14},
  {name:'CANALETE', code: '090', departament_id: 14},
  {name:'AYAPEL', code: '068', departament_id: 14},
  {name:'MONTELIBANO', code: '466', departament_id: 14},
  {name:'SAN PELAYO', code: '686', departament_id: 14},
  {name:'SAN ANTERO', code: '672', departament_id: 14},
  {name:'SAN ANDRES SOTAVENTO', code: '670', departament_id: 14},
  {name:'VALENCIA', code: '855', departament_id: 14},
  {name:'CHIMA', code: '168', departament_id: 14},
  {name:'CHINU', code: '182', departament_id: 14},
  {name:'MONITOS', code: '500', departament_id: 14},
  {name:'MOMIL', code: '464', departament_id: 14},
  {name:'COTORRA', code: '300', departament_id: 14},
  {name:'PUERTO LIBERTADOR', code: '580', departament_id: 14},
  {name:'PURISIMA', code: '586', departament_id: 14},
  {name:'CERETE', code: '162', departament_id: 14},
  {name:'SAHAGUN', code: '660', departament_id: 14},
  {name:'TIERRALTA', code: '807', departament_id: 14},
  {name:'MONTERIA', code: '001', departament_id: 14},
  {name:'TUCHIN', code: '815', departament_id: 14},
  {name:'SAN JOSE DE URE', code: '682', departament_id: 14},
  {name:'LA APARTADA', code: '350', departament_id: 14},
  {name:'PUEBLO NUEVO', code: '570', departament_id: 14},
  {name:'LORICA', code: '417', departament_id: 14},
  {name:'SILVANIA', code: '743', departament_id: 15},
  {name:'NEMOCON', code: '486', departament_id: 15},
  {name:'TABIO', code: '785', departament_id: 15},
  {name:'PAIME', code: '518', departament_id: 15},
  {name:'GUATAVITA', code: '326', departament_id: 15},
  {name:'ANOLAIMA', code: '040', departament_id: 15},
  {name:'FUSAGASUGA', code: '290', departament_id: 15},
  {name:'ANAPOIMA', code: '035', departament_id: 15},
  {name:'NILO', code: '488', departament_id: 15},
  {name:'VILLAPINZON', code: '873', departament_id: 15},
  {name:'SAN BERNARDO', code: '649', departament_id: 15},
  {name:'VILLETA', code: '875', departament_id: 15},
  {name:'QUETAME', code: '594', departament_id: 15},
  {name:'PARATEBUENO', code: '530', departament_id: 15},
  {name:'GUACHETA', code: '317', departament_id: 15},
  {name:'AGUA DE DIOS', code: '001', departament_id: 15},
  {name:'LA PENA', code: '398', departament_id: 15},
  {name:'APULO', code: '599', departament_id: 15},
  {name:'SASAIMA', code: '718', departament_id: 15},
  {name:'UTICA', code: '851', departament_id: 15},
  {name:'CACHIPAY', code: '123', departament_id: 15},
  {name:'COGUA', code: '200', departament_id: 15},
  {name:'TOCAIMA', code: '815', departament_id: 15},
  {name:'SAN ANTONIO DEL TEQUENDAMA', code: '645', departament_id: 15},
  {name:'SUTATAUSA', code: '781', departament_id: 15},
  {name:'PANDI', code: '524', departament_id: 15},
  {name:'QUEBRADANEGRA', code: '592', departament_id: 15},
  {name:'JERUSALEN', code: '368', departament_id: 15},
  {name:'MACHETA', code: '426', departament_id: 15},
  {name:'CAQUEZA', code: '151', departament_id: 15},
  {name:'VILLA DE SAN DIEGO DE UBATE', code: '843', departament_id: 15},
  {name:'GUATAQUI', code: '324', departament_id: 15},
  {name:'FOMEQUE', code: '279', departament_id: 15},
  {name:'NOCAIMA', code: '491', departament_id: 15},
  {name:'CHIA', code: '175', departament_id: 15},
  {name:'PULI', code: '580', departament_id: 15},
  {name:'SOACHA', code: '754', departament_id: 15},
  {name:'FOSCA', code: '281', departament_id: 15},
  {name:'CAPARRAPI', code: '148', departament_id: 15},
  {name:'RICAURTE', code: '612', departament_id: 15},
  {name:'GUAYABAL DE SIQUIMA', code: '328', departament_id: 15},
  {name:'SAN CAYETANO', code: '653', departament_id: 15},
  {name:'BITUIMA', code: '095', departament_id: 15},
  {name:'CAJICA', code: '126', departament_id: 15},
  {name:'LENGUAZAQUE', code: '407', departament_id: 15},
  {name:'EL COLEGIO', code: '245', departament_id: 15},
  {name:'NARINO', code: '483', departament_id: 15},
  {name:'VILLAGOMEZ', code: '871', departament_id: 15},
  {name:'CHOCONTA', code: '183', departament_id: 15},
  {name:'GUTIERREZ', code: '339', departament_id: 15},
  {name:'TOCANCIPA', code: '817', departament_id: 15},
  {name:'MANTA', code: '436', departament_id: 15},
  {name:'TIBACUY', code: '805', departament_id: 15},
  {name:'CHIPAQUE', code: '178', departament_id: 15},
  {name:'CABRERA', code: '120', departament_id: 15},
  {name:'PUERTO SALGAR', code: '572', departament_id: 15},
  {name:'UBAQUE', code: '841', departament_id: 15},
  {name:'GUAYABETAL', code: '335', departament_id: 15},
  {name:'TENA', code: '797', departament_id: 15},
  {name:'SESQUILE', code: '736', departament_id: 15},
  {name:'QUIPILE', code: '596', departament_id: 15},
  {name:'GACHALA', code: '293', departament_id: 15},
  {name:'YACOPI', code: '885', departament_id: 15},
  {name:'GACHETA', code: '297', departament_id: 15},
  {name:'MADRID', code: '430', departament_id: 15},
  {name:'COTA', code: '214', departament_id: 15},
  {name:'MOSQUERA', code: '473', departament_id: 15},
  {name:'GAMA', code: '299', departament_id: 15},
  {name:'TAUSA', code: '793', departament_id: 15},
  {name:'LA PALMA', code: '394', departament_id: 15},
  {name:'VIOTA', code: '878', departament_id: 15},
  {name:'PACHO', code: '513', departament_id: 15},
  {name:'SUPATA', code: '777', departament_id: 15},
  {name:'EL PENON', code: '258', departament_id: 15},
  {name:'LA MESA', code: '386', departament_id: 15},
  {name:'GUASCA', code: '322', departament_id: 15},
  {name:'SUSA', code: '779', departament_id: 15},
  {name:'MEDINA', code: '438', departament_id: 15},
  {name:'SIBATE', code: '740', departament_id: 15},
  {name:'UNE', code: '845', departament_id: 15},
  {name:'GUADUAS', code: '320', departament_id: 15},
  {name:'SUESCA', code: '772', departament_id: 15},
  {name:'SAN JUAN DE RIO SECO', code: '662', departament_id: 15},
  {name:'FUNZA', code: '286', departament_id: 15},
  {name:'CHOACHI', code: '181', departament_id: 15},
  {name:'FUQUENE', code: '288', departament_id: 15},
  {name:'BOJACA', code: '099', departament_id: 15},
  {name:'SIMIJACA', code: '745', departament_id: 15},
  {name:'SUBACHOQUE', code: '769', departament_id: 15},
  {name:'ZIPAQUIRA', code: '899', departament_id: 15},
  {name:'EL ROSAL', code: '260', departament_id: 15},
  {name:'TOPAIPI', code: '823', departament_id: 15},
  {name:'GRANADA', code: '312', departament_id: 15},
  {name:'VIANI', code: '867', departament_id: 15},
  {name:'BELTRAN', code: '086', departament_id: 15},
  {name:'CHAGUANI', code: '168', departament_id: 15},
  {name:'ZIPACON', code: '898', departament_id: 15},
  {name:'LA VEGA', code: '402', departament_id: 15},
  {name:'VENECIA', code: '506', departament_id: 15},
  {name:'CARMEN DE CARUPA', code: '154', departament_id: 15},
  {name:'VERGARA', code: '862', departament_id: 15},
  {name:'CUCUNUBA', code: '224', departament_id: 15},
  {name:'TENJO', code: '799', departament_id: 15},
  {name:'ALBAN', code: '019', departament_id: 15},
  {name:'NIMAIMA', code: '489', departament_id: 15},
  {name:'JUNIN', code: '372', departament_id: 15},
  {name:'PASCA', code: '535', departament_id: 15},
  {name:'UBALA', code: '839', departament_id: 15},
  {name:'SAN FRANCISCO', code: '658', departament_id: 15},
  {name:'GIRARDOT', code: '307', departament_id: 15},
  {name:'SOPO', code: '758', departament_id: 15},
  {name:'ARBELAEZ', code: '053', departament_id: 15},
  {name:'GACHANCIPA', code: '295', departament_id: 15},
  {name:'FACATATIVA', code: '269', departament_id: 15},
  {name:'LA CALERA', code: '377', departament_id: 15},
  {name:'TIBIRITA', code: '807', departament_id: 15},
  {name:'CACAHUAL', code: '886', departament_id: 16},
  {name:'PANA PANA', code: '887', departament_id: 16},
  {name:'MAPIRIPANA', code: '663', departament_id: 16},
  {name:'MORICHAL', code: '888', departament_id: 16},
  {name:'BARRANCO MINAS', code: '343', departament_id: 16},
  {name:'INIRIDA', code: '001', departament_id: 16},
  {name:'PUERTO COLOMBIA', code: '884', departament_id: 16},
  {name:'LA GUADALUPE', code: '885', departament_id: 16},
  {name:'SAN FELIPE', code: '883', departament_id: 16},
  {name:'CALAMAR', code: '015', departament_id: 17},
  {name:'EL RETORNO', code: '025', departament_id: 17},
  {name:'SAN JOSE DEL GUAVIARE', code: '001', departament_id: 17},
  {name:'MIRAFLORES', code: '200', departament_id: 17},
  {name:'SAN AGUSTIN', code: '668', departament_id: 18},
  {name:'PALERMO', code: '524', departament_id: 18},
  {name:'TARQUI', code: '791', departament_id: 18},
  {name:'HOBO', code: '349', departament_id: 18},
  {name:'LA PLATA', code: '396', departament_id: 18},
  {name:'TIMANA', code: '807', departament_id: 18},
  {name:'NEIVA', code: '001', departament_id: 18},
  {name:'CAMPOALEGRE', code: '132', departament_id: 18},
  {name:'TESALIA', code: '797', departament_id: 18},
  {name:'YAGUARA', code: '885', departament_id: 18},
  {name:'OPORAPA', code: '503', departament_id: 18},
  {name:'SALADOBLANCO', code: '660', departament_id: 18},
  {name:'ELIAS', code: '244', departament_id: 18},
  {name:'COLOMBIA', code: '206', departament_id: 18},
  {name:'VILLAVIEJA', code: '872', departament_id: 18},
  {name:'NATAGA', code: '483', departament_id: 18},
  {name:'PALESTINA', code: '530', departament_id: 18},
  {name:'RIVERA', code: '615', departament_id: 18},
  {name:'ALGECIRAS', code: '020', departament_id: 18},
  {name:'TELLO', code: '799', departament_id: 18},
  {name:'ACEVEDO', code: '006', departament_id: 18},
  {name:'PITALITO', code: '551', departament_id: 18},
  {name:'GUADALUPE', code: '319', departament_id: 18},
  {name:'BARAYA', code: '078', departament_id: 18},
  {name:'AIPE', code: '016', departament_id: 18},
  {name:'SANTA MARIA', code: '676', departament_id: 18},
  {name:'LA ARGENTINA', code: '378', departament_id: 18},
  {name:'ALTAMIRA', code: '026', departament_id: 18},
  {name:'GIGANTE', code: '306', departament_id: 18},
  {name:'ISNOS', code: '359', departament_id: 18},
  {name:'PAICOL', code: '518', departament_id: 18},
  {name:'GARZON', code: '298', departament_id: 18},
  {name:'AGRADO', code: '013', departament_id: 18},
  {name:'TERUEL', code: '801', departament_id: 18},
  {name:'IQUIRA', code: '357', departament_id: 18},
  {name:'SUAZA', code: '770', departament_id: 18},
  {name:'PITAL', code: '548', departament_id: 18},
  {name:'DIBULLA', code: '090', departament_id: 19},
  {name:'DISTRACCION', code: '098', departament_id: 19},
  {name:'SAN JUAN DEL CESAR', code: '650', departament_id: 19},
  {name:'MAICAO', code: '430', departament_id: 19},
  {name:'VILLANUEVA', code: '874', departament_id: 19},
  {name:'URIBIA', code: '847', departament_id: 19},
  {name:'BARRANCAS', code: '078', departament_id: 19},
  {name:'ALBANIA', code: '035', departament_id: 19},
  {name:'EL MOLINO', code: '110', departament_id: 19},
  {name:'HATONUEVO', code: '378', departament_id: 19},
  {name:'MANAURE', code: '560', departament_id: 19},
  {name:'FONSECA', code: '279', departament_id: 19},
  {name:'URUMITA', code: '855', departament_id: 19},
  {name:'RIOHACHA', code: '001', departament_id: 19},
  {name:'LA JAGUA DEL PILAR', code: '420', departament_id: 19},
  {name:'PLATO', code: '555', departament_id: 20},
  {name:'ARIGUANI', code: '058', departament_id: 20},
  {name:'CHIVOLO', code: '170', departament_id: 20},
  {name:'SANTA ANA', code: '707', departament_id: 20},
  {name:'ALGARROBO', code: '030', departament_id: 20},
  {name:'EL PINON', code: '258', departament_id: 20},
  {name:'SALAMINA', code: '675', departament_id: 20},
  {name:'SAN SEBASTIAN DE BUENAVISTA', code: '692', departament_id: 20},
  {name:'EL RETEN', code: '268', departament_id: 20},
  {name:'PIVIJAY', code: '551', departament_id: 20},
  {name:'ARACATACA', code: '053', departament_id: 20},
  {name:'CONCORDIA', code: '205', departament_id: 20},
  {name:'EL BANCO', code: '245', departament_id: 20},
  {name:'PEDRAZA', code: '541', departament_id: 20},
  {name:'REMOLINO', code: '605', departament_id: 20},
  {name:'CIENAGA', code: '189', departament_id: 20},
  {name:'GUAMAL', code: '318', departament_id: 20},
  {name:'NUEVA GRANADA', code: '460', departament_id: 20},
  {name:'SANTA MARTA', code: '001', departament_id: 20},
  {name:'ZAPAYAN', code: '960', departament_id: 20},
  {name:'CERRO SAN ANTONIO', code: '161', departament_id: 20},
  {name:'SANTA BARBARA DE PINTO', code: '720', departament_id: 20},
  {name:'PUEBLOVIEJO', code: '570', departament_id: 20},
  {name:'TENERIFE', code: '798', departament_id: 20},
  {name:'SABANAS DE SAN ANGEL', code: '660', departament_id: 20},
  {name:'PIJINO DEL CARMEN', code: '545', departament_id: 20},
  {name:'SAN ZENON', code: '703', departament_id: 20},
  {name:'FUNDACION', code: '288', departament_id: 20},
  {name:'ZONA BANANERA', code: '980', departament_id: 20},
  {name:'SITIONUEVO', code: '745', departament_id: 20},
  {name:'GRANADA', code: '313', departament_id: 21},
  {name:'PUERTO LOPEZ', code: '573', departament_id: 21},
  {name:'MAPIRIPAN', code: '325', departament_id: 21},
  {name:'CABUYARO', code: '124', departament_id: 21},
  {name:'SAN JUANITO', code: '686', departament_id: 21},
  {name:'PUERTO LLERAS', code: '577', departament_id: 21},
  {name:'RESTREPO', code: '606', departament_id: 21},
  {name:'SAN JUAN DE ARAMA', code: '683', departament_id: 21},
  {name:'EL CASTILLO', code: '251', departament_id: 21},
  {name:'PUERTO GAITAN', code: '568', departament_id: 21},
  {name:'EL DORADO', code: '270', departament_id: 21},
  {name:'VISTAHERMOSA', code: '711', departament_id: 21},
  {name:'FUENTE DE ORO', code: '287', departament_id: 21},
  {name:'PUERTO RICO', code: '590', departament_id: 21},
  {name:'URIBE', code: '370', departament_id: 21},
  {name:'SAN CARLOS DE GUAROA', code: '680', departament_id: 21},
  {name:'GUAMAL', code: '318', departament_id: 21},
  {name:'CASTILLA LA NUEVA', code: '150', departament_id: 21},
  {name:'EL CALVARIO', code: '245', departament_id: 21},
  {name:'MESETAS', code: '330', departament_id: 21},
  {name:'ACACIAS', code: '006', departament_id: 21},
  {name:'CUBARRAL', code: '223', departament_id: 21},
  {name:'VILLAVICENCIO', code: '001', departament_id: 21},
  {name:'CUMARAL', code: '226', departament_id: 21},
  {name:'PUERTO CONCORDIA', code: '450', departament_id: 21},
  {name:'LA MACARENA', code: '350', departament_id: 21},
  {name:'LEJANIAS', code: '400', departament_id: 21},
  {name:'SAN MARTIN', code: '689', departament_id: 21},
  {name:'BARRANCA DE UPIA', code: '110', departament_id: 21},
  {name:'PUERRES', code: '573', departament_id: 22},
  {name:'GUACHUCAL', code: '317', departament_id: 22},
  {name:'GUALMATAN', code: '323', departament_id: 22},
  {name:'CUMBAL', code: '227', departament_id: 22},
  {name:'OSPINA', code: '506', departament_id: 22},
  {name:'SAN BERNARDO', code: '685', departament_id: 22},
  {name:'EL TAMBO', code: '260', departament_id: 22},
  {name:'LA CRUZ', code: '378', departament_id: 22},
  {name:'MOSQUERA', code: '473', departament_id: 22},
  {name:'GUAITARILLA', code: '320', departament_id: 22},
  {name:'SANTACRUZ', code: '699', departament_id: 22},
  {name:'TAMINANGO', code: '786', departament_id: 22},
  {name:'MAGUI', code: '427', departament_id: 22},
  {name:'BUESACO', code: '110', departament_id: 22},
  {name:'ALBAN', code: '019', departament_id: 22},
  {name:'SAN PEDRO DE CARTAGO', code: '694', departament_id: 22},
  {name:'ARBOLEDA', code: '051', departament_id: 22},
  {name:'POTOSI', code: '560', departament_id: 22},
  {name:'EL ROSARIO', code: '256', departament_id: 22},
  {name:'LA TOLA', code: '390', departament_id: 22},
  {name:'CORDOBA', code: '215', departament_id: 22},
  {name:'CUMBITARA', code: '233', departament_id: 22},
  {name:'FUNES', code: '287', departament_id: 22},
  {name:'PROVIDENCIA', code: '565', departament_id: 22},
  {name:'COLON', code: '203', departament_id: 22},
  {name:'ROBERTO PAYAN', code: '621', departament_id: 22},
  {name:'EL CHARCO', code: '250', departament_id: 22},
  {name:'CUASPUD', code: '224', departament_id: 22},
  {name:'SAPUYES', code: '720', departament_id: 22},
  {name:'LA UNION', code: '399', departament_id: 22},
  {name:'SANTA BARBARA', code: '696', departament_id: 22},
  {name:'SAN LORENZO', code: '687', departament_id: 22},
  {name:'ALDANA', code: '022', departament_id: 22},
  {name:'BARBACOAS', code: '079', departament_id: 22},
  {name:'CONTADERO', code: '210', departament_id: 22},
  {name:'IPIALES', code: '356', departament_id: 22},
  {name:'PASTO', code: '001', departament_id: 22},
  {name:'RICAURTE', code: '612', departament_id: 22},
  {name:'SAMANIEGO', code: '678', departament_id: 22},
  {name:'EL TABLON DE GOMEZ', code: '258', departament_id: 22},
  {name:'TUQUERRES', code: '838', departament_id: 22},
  {name:'NARINO', code: '480', departament_id: 22},
  {name:'BELEN', code: '083', departament_id: 22},
  {name:'IMUES', code: '354', departament_id: 22},
  {name:'ILES', code: '352', departament_id: 22},
  {name:'POLICARPA', code: '540', departament_id: 22},
  {name:'OLAYA HERRERA', code: '490', departament_id: 22},
  {name:'SANDONA', code: '683', departament_id: 22},
  {name:'FRANCISCO PIZARRO', code: '520', departament_id: 22},
  {name:'EL PENOL', code: '254', departament_id: 22},
  {name:'YACUANQUER', code: '885', departament_id: 22},
  {name:'SAN PABLO', code: '693', departament_id: 22},
  {name:'ANCUYA', code: '036', departament_id: 22},
  {name:'LA FLORIDA', code: '381', departament_id: 22},
  {name:'PUPIALES', code: '585', departament_id: 22},
  {name:'CHACHAGUI', code: '240', departament_id: 22},
  {name:'LA LLANADA', code: '385', departament_id: 22},
  {name:'SAN ANDRES DE TUMACO', code: '835', departament_id: 22},
  {name:'TANGUA', code: '788', departament_id: 22},
  {name:'LINARES', code: '411', departament_id: 22},
  {name:'LOS ANDES', code: '418', departament_id: 22},
  {name:'CONSACA', code: '207', departament_id: 22},
  {name:'LEIVA', code: '405', departament_id: 22},
  {name:'MALLAMA', code: '435', departament_id: 22},
  {name:'EL ZULIA', code: '261', departament_id: 23},
  {name:'SANTIAGO', code: '680', departament_id: 23},
  {name:'PUERTO SANTANDER', code: '553', departament_id: 23},
  {name:'HACARI', code: '344', departament_id: 23},
  {name:'TIBU', code: '810', departament_id: 23},
  {name:'SILOS', code: '743', departament_id: 23},
  {name:'CHITAGA', code: '174', departament_id: 23},
  {name:'OCANA', code: '498', departament_id: 23},
  {name:'HERRAN', code: '347', departament_id: 23},
  {name:'BOCHALEMA', code: '099', departament_id: 23},
  {name:'CONVENCION', code: '206', departament_id: 23},
  {name:'CACOTA', code: '125', departament_id: 23},
  {name:'ABREGO', code: '003', departament_id: 23},
  {name:'LA PLAYA', code: '398', departament_id: 23},
  {name:'BUCARASICA', code: '109', departament_id: 23},
  {name:'SALAZAR', code: '660', departament_id: 23},
  {name:'EL TARRA', code: '250', departament_id: 23},
  {name:'LOS PATIOS', code: '405', departament_id: 23},
  {name:'VILLA CARO', code: '871', departament_id: 23},
  {name:'LOURDES', code: '418', departament_id: 23},
  {name:'PAMPLONITA', code: '520', departament_id: 23},
  {name:'ARBOLEDAS', code: '051', departament_id: 23},
  {name:'LABATECA', code: '377', departament_id: 23},
  {name:'VILLA DEL ROSARIO', code: '874', departament_id: 23},
  {name:'RAGONVALIA', code: '599', departament_id: 23},
  {name:'CUCUTILLA', code: '223', departament_id: 23},
  {name:'EL CARMEN', code: '245', departament_id: 23},
  {name:'PAMPLONA', code: '518', departament_id: 23},
  {name:'CUCUTA', code: '001', departament_id: 23},
  {name:'DURANIA', code: '239', departament_id: 23},
  {name:'CHINACOTA', code: '172', departament_id: 23},
  {name:'SARDINATA', code: '720', departament_id: 23},
  {name:'TEORAMA', code: '800', departament_id: 23},
  {name:'MUTISCUA', code: '480', departament_id: 23},
  {name:'SAN CAYETANO', code: '673', departament_id: 23},
  {name:'GRAMALOTE', code: '313', departament_id: 23},
  {name:'SAN CALIXTO', code: '670', departament_id: 23},
  {name:'CACHIRA', code: '128', departament_id: 23},
  {name:'TOLEDO', code: '820', departament_id: 23},
  {name:'LA ESPERANZA', code: '385', departament_id: 23},
  {name:'SANTIAGO', code: '760', departament_id: 24},
  {name:'SIBUNDOY', code: '749', departament_id: 24},
  {name:'VALLE DEL GUAMUEZ', code: '865', departament_id: 24},
  {name:'ORITO', code: '320', departament_id: 24},
  {name:'VILLAGARZON', code: '885', departament_id: 24},
  {name:'SAN FRANCISCO', code: '755', departament_id: 24},
  {name:'PUERTO LEGUIZAMO', code: '573', departament_id: 24},
  {name:'SAN MIGUEL', code: '757', departament_id: 24},
  {name:'PUERTO GUZMAN', code: '571', departament_id: 24},
  {name:'PUERTO CAICEDO', code: '569', departament_id: 24},
  {name:'COLON', code: '219', departament_id: 24},
  {name:'PUERTO ASIS', code: '568', departament_id: 24},
  {name:'MOCOA', code: '001', departament_id: 24},
  {name:'CALARCA', code: '130', departament_id: 25},
  {name:'BUENAVISTA', code: '111', departament_id: 25},
  {name:'MONTENEGRO', code: '470', departament_id: 25},
  {name:'LA TEBAIDA', code: '401', departament_id: 25},
  {name:'QUIMBAYA', code: '594', departament_id: 25},
  {name:'GENOVA', code: '302', departament_id: 25},
  {name:'CORDOBA', code: '212', departament_id: 25},
  {name:'SALENTO', code: '690', departament_id: 25},
  {name:'PIJAO', code: '548', departament_id: 25},
  {name:'FILANDIA', code: '272', departament_id: 25},
  {name:'ARMENIA', code: '001', departament_id: 25},
  {name:'CIRCASIA', code: '190', departament_id: 25},
  {name:'MARSELLA', code: '440', departament_id: 26},
  {name:'LA VIRGINIA', code: '400', departament_id: 26},
  {name:'MISTRATO', code: '456', departament_id: 26},
  {name:'QUINCHIA', code: '594', departament_id: 26},
  {name:'APIA', code: '045', departament_id: 26},
  {name:'DOSQUEBRADAS', code: '170', departament_id: 26},
  {name:'PEREIRA', code: '001', departament_id: 26},
  {name:'SANTA ROSA DE CABAL', code: '682', departament_id: 26},
  {name:'SANTUARIO', code: '687', departament_id: 26},
  {name:'BELEN DE UMBRIA', code: '088', departament_id: 26},
  {name:'GUATICA', code: '318', departament_id: 26},
  {name:'LA CELIA', code: '383', departament_id: 26},
  {name:'BALBOA', code: '075', departament_id: 26},
  {name:'PUEBLO RICO', code: '572', departament_id: 26},
  {name:'SAN ANDRES', code: '001', departament_id: 27},
  {name:'PROVIDENCIA', code: '564', departament_id: 27},
  {name:'BETULIA', code: '092', departament_id: 28},
  {name:'OCAMONTE', code: '498', departament_id: 28},
  {name:'PALMAR', code: '522', departament_id: 28},
  {name:'AGUADA', code: '013', departament_id: 28},
  {name:'GUAVATA', code: '324', departament_id: 28},
  {name:'BARBOSA', code: '077', departament_id: 28},
  {name:'SAN JOAQUIN', code: '682', departament_id: 28},
  {name:'SAN ANDRES', code: '669', departament_id: 28},
  {name:'SANTA HELENA DEL OPON', code: '720', departament_id: 28},
  {name:'CONCEPCION', code: '207', departament_id: 28},
  {name:'SANTA BARBARA', code: '705', departament_id: 28},
  {name:'CURITI', code: '229', departament_id: 28},
  {name:'ENCISO', code: '266', departament_id: 28},
  {name:'BARRANCABERMEJA', code: '081', departament_id: 28},
  {name:'CIMITARRA', code: '190', departament_id: 28},
  {name:'MOGOTES', code: '464', departament_id: 28},
  {name:'BOLIVAR', code: '101', departament_id: 28},
  {name:'PIEDECUESTA', code: '547', departament_id: 28},
  {name:'CHIMA', code: '176', departament_id: 28},
  {name:'JESUS MARIA', code: '368', departament_id: 28},
  {name:'GALAN', code: '296', departament_id: 28},
  {name:'LA PAZ', code: '397', departament_id: 28},
  {name:'OIBA', code: '500', departament_id: 28},
  {name:'RIONEGRO', code: '615', departament_id: 28},
  {name:'SUAITA', code: '770', departament_id: 28},
  {name:'HATO', code: '344', departament_id: 28},
  {name:'SAN BENITO', code: '673', departament_id: 28},
  {name:'FLORIDABLANCA', code: '276', departament_id: 28},
  {name:'LA BELLEZA', code: '377', departament_id: 28},
  {name:'MACARAVITA', code: '425', departament_id: 28},
  {name:'GUEPSA', code: '327', departament_id: 28},
  {name:'PUERTO WILCHES', code: '575', departament_id: 28},
  {name:'TONA', code: '820', departament_id: 28},
  {name:'GUACA', code: '318', departament_id: 28},
  {name:'ARATOCA', code: '051', departament_id: 28},
  {name:'CONFINES', code: '209', departament_id: 28},
  {name:'LANDAZURI', code: '385', departament_id: 28},
  {name:'CABRERA', code: '121', departament_id: 28},
  {name:'PUENTE NACIONAL', code: '572', departament_id: 28},
  {name:'SAN JOSE DE MIRANDA', code: '684', departament_id: 28},
  {name:'BUCARAMANGA', code: '001', departament_id: 28},
  {name:'PINCHOTE', code: '549', departament_id: 28},
  {name:'CHIPATA', code: '179', departament_id: 28},
  {name:'ZAPATOCA', code: '895', departament_id: 28},
  {name:'LOS SANTOS', code: '418', departament_id: 28},
  {name:'VETAS', code: '867', departament_id: 28},
  {name:'SUCRE', code: '773', departament_id: 28},
  {name:'COROMORO', code: '217', departament_id: 28},
  {name:'ALBANIA', code: '020', departament_id: 28},
  {name:'ONZAGA', code: '502', departament_id: 28},
  {name:'EL PLAYON', code: '255', departament_id: 28},
  {name:'ENCINO', code: '264', departament_id: 28},
  {name:'PALMAS DEL SOCORRO', code: '524', departament_id: 28},
  {name:'CAPITANEJO', code: '147', departament_id: 28},
  {name:'PUERTO PARRA', code: '573', departament_id: 28},
  {name:'CEPITA', code: '160', departament_id: 28},
  {name:'LEBRIJA', code: '406', departament_id: 28},
  {name:'VILLANUEVA', code: '872', departament_id: 28},
  {name:'SIMACOTA', code: '745', departament_id: 28},
  {name:'MATANZA', code: '444', departament_id: 28},
  {name:'SAN MIGUEL', code: '686', departament_id: 28},
  {name:'CONTRATACION', code: '211', departament_id: 28},
  {name:'PARAMO', code: '533', departament_id: 28},
  {name:'EL GUACAMAYO', code: '245', departament_id: 28},
  {name:'CHARTA', code: '169', departament_id: 28},
  {name:'SABANA DE TORRES', code: '655', departament_id: 28},
  {name:'SAN GIL', code: '679', departament_id: 28},
  {name:'CALIFORNIA', code: '132', departament_id: 28},
  {name:'CERRITO', code: '162', departament_id: 28},
  {name:'MOLAGAVITA', code: '468', departament_id: 28},
  {name:'GUAPOTA', code: '322', departament_id: 28},
  {name:'GAMBITA', code: '298', departament_id: 28},
  {name:'EL CARMEN DE CHUCURI', code: '235', departament_id: 28},
  {name:'CARCASI', code: '152', departament_id: 28},
  {name:'FLORIAN', code: '271', departament_id: 28},
  {name:'SAN VICENTE DE CHUCURI', code: '689', departament_id: 28},
  {name:'SURATA', code: '780', departament_id: 28},
  {name:'JORDAN', code: '370', departament_id: 28},
  {name:'GIRON', code: '307', departament_id: 28},
  {name:'EL PENON', code: '250', departament_id: 28},
  {name:'MALAGA', code: '432', departament_id: 28},
  {name:'GUADALUPE', code: '320', departament_id: 28},
  {name:'BARICHARA', code: '079', departament_id: 28},
  {name:'VELEZ', code: '861', departament_id: 28},
  {name:'CHARALA', code: '167', departament_id: 28},
  {name:'SOCORRO', code: '755', departament_id: 28},
  {name:'VALLE DE SAN JOSE', code: '855', departament_id: 28},
  {name:'BUENAVISTA', code: '110', departament_id: 29},
  {name:'GALERAS', code: '235', departament_id: 29},
  {name:'SINCELEJO', code: '001', departament_id: 29},
  {name:'LOS PALMITOS', code: '418', departament_id: 29},
  {name:'CHALAN', code: '230', departament_id: 29},
  {name:'CAIMITO', code: '124', departament_id: 29},
  {name:'OVEJAS', code: '508', departament_id: 29},
  {name:'TOLU VIEJO', code: '823', departament_id: 29},
  {name:'MORROA', code: '473', departament_id: 29},
  {name:'GUARANDA', code: '265', departament_id: 29},
  {name:'COVENAS', code: '221', departament_id: 29},
  {name:'PALMITO', code: '523', departament_id: 29},
  {name:'SAN JUAN DE BETULIA', code: '702', departament_id: 29},
  {name:'SANTIAGO DE TOLU', code: '820', departament_id: 29},
  {name:'LA UNION', code: '400', departament_id: 29},
  {name:'COLOSO', code: '204', departament_id: 29},
  {name:'EL ROBLE', code: '233', departament_id: 29},
  {name:'SAN PEDRO', code: '717', departament_id: 29},
  {name:'SAN MARCOS', code: '708', departament_id: 29},
  {name:'SAN LUIS DE SINCE', code: '742', departament_id: 29},
  {name:'MAJAGUAL', code: '429', departament_id: 29},
  {name:'SAMPUES', code: '670', departament_id: 29},
  {name:'COROZAL', code: '215', departament_id: 29},
  {name:'SAN BENITO ABAD', code: '678', departament_id: 29},
  {name:'SAN ONOFRE', code: '713', departament_id: 29},
  {name:'SUCRE', code: '771', departament_id: 29},
  {name:'ARMERO', code: '055', departament_id: 30},
  {name:'DOLORES', code: '236', departament_id: 30},
  {name:'LERIDA', code: '408', departament_id: 30},
  {name:'CHAPARRAL', code: '168', departament_id: 30},
  {name:'HONDA', code: '349', departament_id: 30},
  {name:'VILLARRICA', code: '873', departament_id: 30},
  {name:'CARMEN DE APICALA', code: '148', departament_id: 30},
  {name:'SAN SEBASTIAN DE MARIQUITA', code: '443', departament_id: 30},
  {name:'VALLE DE SAN JUAN', code: '854', departament_id: 30},
  {name:'FRESNO', code: '283', departament_id: 30},
  {name:'GUAMO', code: '319', departament_id: 30},
  {name:'SANTA ISABEL', code: '686', departament_id: 30},
  {name:'SALDANA', code: '671', departament_id: 30},
  {name:'NATAGAIMA', code: '483', departament_id: 30},
  {name:'CAJAMARCA', code: '124', departament_id: 30},
  {name:'ALVARADO', code: '026', departament_id: 30},
  {name:'SAN ANTONIO', code: '675', departament_id: 30},
  {name:'ROVIRA', code: '624', departament_id: 30},
  {name:'COELLO', code: '200', departament_id: 30},
  {name:'FALAN', code: '270', departament_id: 30},
  {name:'IBAGUE', code: '001', departament_id: 30},
  {name:'RIOBLANCO', code: '616', departament_id: 30},
  {name:'ANZOATEGUI', code: '043', departament_id: 30},
  {name:'COYAIMA', code: '217', departament_id: 30},
  {name:'SUAREZ', code: '770', departament_id: 30},
  {name:'MURILLO', code: '461', departament_id: 30},
  {name:'PIEDRAS', code: '547', departament_id: 30},
  {name:'SAN LUIS', code: '678', departament_id: 30},
  {name:'VENADILLO', code: '861', departament_id: 30},
  {name:'FLANDES', code: '275', departament_id: 30},
  {name:'ICONONZO', code: '352', departament_id: 30},
  {name:'CUNDAY', code: '226', departament_id: 30},
  {name:'ALPUJARRA', code: '024', departament_id: 30},
  {name:'RONCESVALLES', code: '622', departament_id: 30},
  {name:'ESPINAL', code: '268', departament_id: 30},
  {name:'PRADO', code: '563', departament_id: 30},
  {name:'AMBALEMA', code: '030', departament_id: 30},
  {name:'HERVEO', code: '347', departament_id: 30},
  {name:'LIBANO', code: '411', departament_id: 30},
  {name:'ATACO', code: '067', departament_id: 30},
  {name:'MELGAR', code: '449', departament_id: 30},
  {name:'ORTEGA', code: '504', departament_id: 30},
  {name:'PURIFICACION', code: '585', departament_id: 30},
  {name:'VILLAHERMOSA', code: '870', departament_id: 30},
  {name:'PALOCABILDO', code: '520', departament_id: 30},
  {name:'CASABIANCA', code: '152', departament_id: 30},
  {name:'PLANADAS', code: '555', departament_id: 30},
  {name:'ALCALA', code: '020', departament_id: 31},
  {name:'LA CUMBRE', code: '377', departament_id: 31},
  {name:'EL CAIRO', code: '246', departament_id: 31},
  {name:'RIOFRIO', code: '616', departament_id: 31},
  {name:'ROLDANILLO', code: '622', departament_id: 31},
  {name:'EL AGUILA', code: '243', departament_id: 31},
  {name:'BUGALAGRANDE', code: '113', departament_id: 31},
  {name:'OBANDO', code: '497', departament_id: 31},
  {name:'ANDALUCIA', code: '036', departament_id: 31},
  {name:'BUENAVENTURA', code: '109', departament_id: 31},
  {name:'GUADALAJARA DE BUGA', code: '111', departament_id: 31},
  {name:'BOLIVAR', code: '100', departament_id: 31},
  {name:'ARGELIA', code: '054', departament_id: 31},
  {name:'CALI', code: '001', departament_id: 31},
  {name:'TULUA', code: '834', departament_id: 31},
  {name:'SAN PEDRO', code: '670', departament_id: 31},
  {name:'ZARZAL', code: '895', departament_id: 31},
  {name:'VIJES', code: '869', departament_id: 31},
  {name:'DAGUA', code: '233', departament_id: 31},
  {name:'CANDELARIA', code: '130', departament_id: 31},
  {name:'RESTREPO', code: '606', departament_id: 31},
  {name:'YUMBO', code: '892', departament_id: 31},
  {name:'TRUJILLO', code: '828', departament_id: 31},
  {name:'CARTAGO', code: '147', departament_id: 31},
  {name:'LA VICTORIA', code: '403', departament_id: 31},
  {name:'YOTOCO', code: '890', departament_id: 31},
  {name:'EL DOVIO', code: '250', departament_id: 31},
  {name:'TORO', code: '823', departament_id: 31},
  {name:'SEVILLA', code: '736', departament_id: 31},
  {name:'PALMIRA', code: '520', departament_id: 31},
  {name:'VERSALLES', code: '863', departament_id: 31},
  {name:'CALIMA', code: '126', departament_id: 31},
  {name:'FLORIDA', code: '275', departament_id: 31},
  {name:'CAICEDONIA', code: '122', departament_id: 31},
  {name:'PRADERA', code: '563', departament_id: 31},
  {name:'GINEBRA', code: '306', departament_id: 31},
  {name:'ANSERMANUEVO', code: '041', departament_id: 31},
  {name:'ULLOA', code: '845', departament_id: 31},
  {name:'JAMUNDI', code: '364', departament_id: 31},
  {name:'LA UNION', code: '400', departament_id: 31},
  {name:'GUACARI', code: '318', departament_id: 31},
  {name:'EL CERRITO', code: '248', departament_id: 31},
  {name:'PAPUNAUA', code: '777', departament_id: 32},
  {name:'CARURU', code: '161', departament_id: 32},
  {name:'MITU', code: '001', departament_id: 32},
  {name:'YAVARATE', code: '889', departament_id: 32},
  {name:'TARAIRA', code: '666', departament_id: 32},
  {name:'PACOA', code: '511', departament_id: 32},
  {name:'CUMARIBO', code: '773', departament_id: 33},
  {name:'PUERTO CARRENO', code: '001', departament_id: 33},
  {name:'LA PRIMAVERA', code: '524', departament_id: 33},
  {name:'SANTA ROSALIA', code: '624', departament_id: 33}
])

IdentificationType.create([
    {name: 'CÉDULA DE CIUDADANÍA', code: '01'},
    {name: 'CÉDULA DE EXTRANJERÍA', code: '02'},
    {name: 'PASAPORTE', code: '03'}
])

Area.create([
    {id: 0, name: 'TODAS LAS AREAS', code: '000'},
    {name: 'PRESIDENCIA', code: '001'},
    {name: 'VICEPRESIDENCIA', code: '002', area_id: 1},
    {name: 'ÁREA CONTABLE', code: '011', area_id: 2}
])

Charge.create([
    {name: 'SECRETARIO', code: '001'},
    {name: 'CONTADOR', code: '002'}
])

ContractType.create([
    {name: 'CONTRATO TÉRMINO INDEFINIDO', code: '001'},
    {name: 'CONTRATO TÉRMINO FIJO', code: '002'},
    {name: 'CONTRATO TEMPORAL', code: '003'}
])

GoalType.create([
    {name: 'EMPRESARIAL', code: '001'}
])

Genre.create([
    {name: 'FEMENINO', code: '01', alias: 'SEÑORA'},
    {name: 'MASCULINO', code: '02', alias: 'SEÑOR'},
    {name: 'OTRO', code: '03', alias: 'SEÑXR'}
])

GenerationRange.create([
    {name: 'MILENNIAL', code: '01'},
    {name: 'GENERACIÓN X', code: '02'},
    {name: 'BABBY BOOMER', code: '03'}
])

Role.create([
    {name: 'ADMINISTRADOR', code: '01'},
    {name: 'USUARIO', code: '02'}
])

User.create([
    {
      document: 1032459412, first_name: 'JONATHAN', first_lastname: 'GRANADOS', email: 'jonathan@gmail.com', password: 'Jon123', password_confirmation: 'Jon123', role_id: 1,
      telephone: 1234, celphone: 1234, address: 'CRA 66', evaluation_role: 3, identification_type_id: 1, area_id: 1, charge_id: 1, genre_id: 1, generation_range_id: 1,
    },{
      document: 1234567890, first_name: 'EVALUADOR', first_lastname: 'TESTEO', email: 'evaluador@gmail.com', password: 'Eval123', password_confirmation: 'Eval123', role_id: 2,
      telephone: 1234, celphone: 1234, address: 'CRA 66', evaluation_role: 3, identification_type_id: 1, area_id: 1, charge_id: 1, genre_id: 1, generation_range_id: 1,
    },{
      document: 1234567890, first_name: 'EVALUADO', first_lastname: 'TESTEO', email: 'evaluado@gmail.com', password: 'Eval123', password_confirmation: 'Eval123', role_id: 2,
      telephone: 1234, celphone: 1234, address: 'CRA 66', evaluation_role: 1, identification_type_id: 1, area_id: 2, charge_id: 1, genre_id: 1, generation_range_id: 1,
    },
])

Goal.create([
    {
      goal_name: 'INDICE DE FRECUENCIA TOTAL DE CASOS REGISTRABLES',
      general_ind: 'INDICE DE FRECUENCIA TOTAL DE CASOS REGISTRABLES',
      specific_ind: 'CUMPLIR CON EL LIMITE DE EVENTOS DE ACCIDENTE CON PERDIDA Y/O FATALIDADES, EVENTOS CON TRABAJO RESTRINGIDO Y EVENTOS CON TRATAMIENTOS MEDICOS',
      code:'001', phases_number: 2, percentaje: 30, goal_type_id: 1, area_id: 0, phases: [Phase.create(proposed: 20), Phase.create(proposed: 20)]
    },{
      goal_name: 'PRODUCCION DE ETANOL',
      general_ind: 'PRODUCTIVIDAD DE PLANTA',
      specific_ind: 'CUMPLIR CON LA PRODUCCION DE ETANOL PROYECTADO EN EL CASO DE NEGOCIO DE BIOENERGY',
      code:'002', phases_number: 2, percentaje: 30, goal_type_id: 1, area_id: 0, phases: [Phase.create(proposed: 20), Phase.create(proposed: 20)]
    },{
      goal_name: 'VENTA DE ENERGIA',
      general_ind: 'PRODUCTIVIDAD DE PLANTA',
      specific_ind: 'CUMPLIR CON LAS VENTAS DE ENERGIA PROYECTADAS EN EL CASO DE NEGOCIO DE BIOENERGY',
      code:'003', phases_number: 2, percentaje: 30, goal_type_id: 1, area_id: 1, phases: [Phase.create(proposed: 20), Phase.create(proposed: 20)]
    },{
      goal_name: 'DIAS EFECTIVOS DE MOLIENDA',
      general_ind: 'PRODUCTIVIDAD DE PLANTA',
      specific_ind: 'CUMPLIR CON LOS DIAS EFECTIVOS DE MOLIENDA DE CAÑA DE ACUERDO A LO PROYECTADO EN EL CASO DE NEGOCIO DE BIOENERGY',
      code:'004', phases_number: 2, percentaje: 40, goal_type_id: 1, area_id: 2, phases: [Phase.create(proposed: 20), Phase.create(proposed: 20)]
    },{
      goal_name: 'EBITDA',
      general_ind: 'EBITDA',
      specific_ind: 'MAXIMIZAR LA AGREGACION DE VALOR PARA LOS ACCIONISTAS',
      code:'005', phases_number: 2, percentaje: 40, goal_type_id: 1, area_id: 3, phases: [Phase.create(proposed: 20), Phase.create(proposed: 20)]
    }
])

Competency.create([
    {
      code: '001', comp_name: 'TRABAJO EN EQUIPO', percentaje: 80, goal_type_id: 1, area_id: 0
    },{
      code: '002', comp_name: 'LIDERAZGO', percentaje: 20, goal_type_id: 1, area_id: 0
    }
])
